package cn.bevol.statics.dao;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hq_composition
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Composition implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.tstamp
     *
     * @mbg.generated
     */
    private Integer tstamp;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.crdate
     *
     * @mbg.generated
     */
    private Integer crdate;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.cruser_id
     *
     * @mbg.generated
     */
    private Integer cruserId;

    /**
     * Database Column Remarks:
     *   删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.deleted
     *
     * @mbg.generated
     */
    private Integer deleted;

    /**
     * Database Column Remarks:
     *   隐藏
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.hidden
     *
     * @mbg.generated
     */
    private Integer hidden;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.sorting
     *
     * @mbg.generated
     */
    private Integer sorting;

    /**
     * Database Column Remarks:
     *   访问次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.hit
     *
     * @mbg.generated
     */
    private Integer hit;

    /**
     * Database Column Remarks:
     *   推荐
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.hot
     *
     * @mbg.generated
     */
    private Integer hot;

    /**
     * Database Column Remarks:
     *   置顶
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.top
     *
     * @mbg.generated
     */
    private Integer top;

    /**
     * Database Column Remarks:
     *   原料中文名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   使用功效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.efficacy
     *
     * @mbg.generated
     */
    private String efficacy;

    /**
     * Database Column Remarks:
     *   英文名（INCI）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.english
     *
     * @mbg.generated
     */
    private String english;

    /**
     * Database Column Remarks:
     *   使用频率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.frequency
     *
     * @mbg.generated
     */
    private Integer frequency;

    /**
     * Database Column Remarks:
     *   活性成分  0为空 1为赞 2为防晒
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.active
     *
     * @mbg.generated
     */
    private String active;

    /**
     * Database Column Remarks:
     *   安全风险 0-2分为绿色  3-6分为橙色 7-10分为红色
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.safety
     *
     * @mbg.generated
     */
    private String safety;

    /**
     * Database Column Remarks:
     *   致粉刺风险
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.acne_risk
     *
     * @mbg.generated
     */
    private Integer acneRisk;

    /**
     * Database Column Remarks:
     *   CAS号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.cas
     *
     * @mbg.generated
     */
    private String cas;

    /**
     * Database Column Remarks:
     *   其他名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.other_title
     *
     * @mbg.generated
     */
    private String otherTitle;

    /**
     * Database Column Remarks:
     *   使用频率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.used_num
     *
     * @mbg.generated
     */
    private Integer usedNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.shenyong
     *
     * @mbg.generated
     */
    private String shenyong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.used
     *
     * @mbg.generated
     */
    private String used;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.used_name
     *
     * @mbg.generated
     */
    private String usedName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.likecount
     *
     * @mbg.generated
     */
    private Integer likecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.commentcount
     *
     * @mbg.generated
     */
    private Integer commentcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.OSPW
     *
     * @mbg.generated
     */
    private String ospw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.OSPT
     *
     * @mbg.generated
     */
    private String ospt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.OSNW
     *
     * @mbg.generated
     */
    private String osnw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.OSNT
     *
     * @mbg.generated
     */
    private String osnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.ORPW
     *
     * @mbg.generated
     */
    private String orpw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.ORNW
     *
     * @mbg.generated
     */
    private String ornw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.ORNT
     *
     * @mbg.generated
     */
    private String ornt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.DSPW
     *
     * @mbg.generated
     */
    private String dspw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.DSPT
     *
     * @mbg.generated
     */
    private String dspt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.DSNW
     *
     * @mbg.generated
     */
    private String dsnw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.DSNT
     *
     * @mbg.generated
     */
    private String dsnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.DRPW
     *
     * @mbg.generated
     */
    private String drpw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.DRPT
     *
     * @mbg.generated
     */
    private String drpt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.DRNW
     *
     * @mbg.generated
     */
    private String drnw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.DRNT
     *
     * @mbg.generated
     */
    private String drnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.ORPT
     *
     * @mbg.generated
     */
    private String orpt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.mid
     *
     * @mbg.generated
     */
    private String mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.mpid
     *
     * @mbg.generated
     */
    private String mpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.namelength
     *
     * @mbg.generated
     */
    private Integer namelength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.u1
     *
     * @mbg.generated
     */
    private Integer u1;

    /**
     * Database Column Remarks:
     *   保留成分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.reserve
     *
     * @mbg.generated
     */
    private Integer reserve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.cm_name
     *
     * @mbg.generated
     */
    private String cmName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_composition.cm_english
     *
     * @mbg.generated
     */
    private String cmEnglish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.id
     *
     * @return the value of hq_composition.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.id
     *
     * @param id the value for hq_composition.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.tstamp
     *
     * @return the value of hq_composition.tstamp
     *
     * @mbg.generated
     */
    public Integer getTstamp() {
        return tstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withTstamp(Integer tstamp) {
        this.setTstamp(tstamp);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.tstamp
     *
     * @param tstamp the value for hq_composition.tstamp
     *
     * @mbg.generated
     */
    public void setTstamp(Integer tstamp) {
        this.tstamp = tstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.crdate
     *
     * @return the value of hq_composition.crdate
     *
     * @mbg.generated
     */
    public Integer getCrdate() {
        return crdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withCrdate(Integer crdate) {
        this.setCrdate(crdate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.crdate
     *
     * @param crdate the value for hq_composition.crdate
     *
     * @mbg.generated
     */
    public void setCrdate(Integer crdate) {
        this.crdate = crdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.cruser_id
     *
     * @return the value of hq_composition.cruser_id
     *
     * @mbg.generated
     */
    public Integer getCruserId() {
        return cruserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withCruserId(Integer cruserId) {
        this.setCruserId(cruserId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.cruser_id
     *
     * @param cruserId the value for hq_composition.cruser_id
     *
     * @mbg.generated
     */
    public void setCruserId(Integer cruserId) {
        this.cruserId = cruserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.deleted
     *
     * @return the value of hq_composition.deleted
     *
     * @mbg.generated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withDeleted(Integer deleted) {
        this.setDeleted(deleted);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.deleted
     *
     * @param deleted the value for hq_composition.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.hidden
     *
     * @return the value of hq_composition.hidden
     *
     * @mbg.generated
     */
    public Integer getHidden() {
        return hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withHidden(Integer hidden) {
        this.setHidden(hidden);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.hidden
     *
     * @param hidden the value for hq_composition.hidden
     *
     * @mbg.generated
     */
    public void setHidden(Integer hidden) {
        this.hidden = hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.sorting
     *
     * @return the value of hq_composition.sorting
     *
     * @mbg.generated
     */
    public Integer getSorting() {
        return sorting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withSorting(Integer sorting) {
        this.setSorting(sorting);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.sorting
     *
     * @param sorting the value for hq_composition.sorting
     *
     * @mbg.generated
     */
    public void setSorting(Integer sorting) {
        this.sorting = sorting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.hit
     *
     * @return the value of hq_composition.hit
     *
     * @mbg.generated
     */
    public Integer getHit() {
        return hit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withHit(Integer hit) {
        this.setHit(hit);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.hit
     *
     * @param hit the value for hq_composition.hit
     *
     * @mbg.generated
     */
    public void setHit(Integer hit) {
        this.hit = hit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.hot
     *
     * @return the value of hq_composition.hot
     *
     * @mbg.generated
     */
    public Integer getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withHot(Integer hot) {
        this.setHot(hot);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.hot
     *
     * @param hot the value for hq_composition.hot
     *
     * @mbg.generated
     */
    public void setHot(Integer hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.top
     *
     * @return the value of hq_composition.top
     *
     * @mbg.generated
     */
    public Integer getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withTop(Integer top) {
        this.setTop(top);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.top
     *
     * @param top the value for hq_composition.top
     *
     * @mbg.generated
     */
    public void setTop(Integer top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.name
     *
     * @return the value of hq_composition.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.name
     *
     * @param name the value for hq_composition.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.efficacy
     *
     * @return the value of hq_composition.efficacy
     *
     * @mbg.generated
     */
    public String getEfficacy() {
        return efficacy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withEfficacy(String efficacy) {
        this.setEfficacy(efficacy);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.efficacy
     *
     * @param efficacy the value for hq_composition.efficacy
     *
     * @mbg.generated
     */
    public void setEfficacy(String efficacy) {
        this.efficacy = efficacy == null ? null : efficacy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.english
     *
     * @return the value of hq_composition.english
     *
     * @mbg.generated
     */
    public String getEnglish() {
        return english;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withEnglish(String english) {
        this.setEnglish(english);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.english
     *
     * @param english the value for hq_composition.english
     *
     * @mbg.generated
     */
    public void setEnglish(String english) {
        this.english = english == null ? null : english.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.frequency
     *
     * @return the value of hq_composition.frequency
     *
     * @mbg.generated
     */
    public Integer getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withFrequency(Integer frequency) {
        this.setFrequency(frequency);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.frequency
     *
     * @param frequency the value for hq_composition.frequency
     *
     * @mbg.generated
     */
    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.active
     *
     * @return the value of hq_composition.active
     *
     * @mbg.generated
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withActive(String active) {
        this.setActive(active);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.active
     *
     * @param active the value for hq_composition.active
     *
     * @mbg.generated
     */
    public void setActive(String active) {
        this.active = active == null ? null : active.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.safety
     *
     * @return the value of hq_composition.safety
     *
     * @mbg.generated
     */
    public String getSafety() {
        return safety;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withSafety(String safety) {
        this.setSafety(safety);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.safety
     *
     * @param safety the value for hq_composition.safety
     *
     * @mbg.generated
     */
    public void setSafety(String safety) {
        this.safety = safety == null ? null : safety.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.acne_risk
     *
     * @return the value of hq_composition.acne_risk
     *
     * @mbg.generated
     */
    public Integer getAcneRisk() {
        return acneRisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withAcneRisk(Integer acneRisk) {
        this.setAcneRisk(acneRisk);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.acne_risk
     *
     * @param acneRisk the value for hq_composition.acne_risk
     *
     * @mbg.generated
     */
    public void setAcneRisk(Integer acneRisk) {
        this.acneRisk = acneRisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.cas
     *
     * @return the value of hq_composition.cas
     *
     * @mbg.generated
     */
    public String getCas() {
        return cas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withCas(String cas) {
        this.setCas(cas);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.cas
     *
     * @param cas the value for hq_composition.cas
     *
     * @mbg.generated
     */
    public void setCas(String cas) {
        this.cas = cas == null ? null : cas.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.other_title
     *
     * @return the value of hq_composition.other_title
     *
     * @mbg.generated
     */
    public String getOtherTitle() {
        return otherTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withOtherTitle(String otherTitle) {
        this.setOtherTitle(otherTitle);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.other_title
     *
     * @param otherTitle the value for hq_composition.other_title
     *
     * @mbg.generated
     */
    public void setOtherTitle(String otherTitle) {
        this.otherTitle = otherTitle == null ? null : otherTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.used_num
     *
     * @return the value of hq_composition.used_num
     *
     * @mbg.generated
     */
    public Integer getUsedNum() {
        return usedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withUsedNum(Integer usedNum) {
        this.setUsedNum(usedNum);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.used_num
     *
     * @param usedNum the value for hq_composition.used_num
     *
     * @mbg.generated
     */
    public void setUsedNum(Integer usedNum) {
        this.usedNum = usedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.shenyong
     *
     * @return the value of hq_composition.shenyong
     *
     * @mbg.generated
     */
    public String getShenyong() {
        return shenyong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withShenyong(String shenyong) {
        this.setShenyong(shenyong);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.shenyong
     *
     * @param shenyong the value for hq_composition.shenyong
     *
     * @mbg.generated
     */
    public void setShenyong(String shenyong) {
        this.shenyong = shenyong == null ? null : shenyong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.used
     *
     * @return the value of hq_composition.used
     *
     * @mbg.generated
     */
    public String getUsed() {
        return used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withUsed(String used) {
        this.setUsed(used);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.used
     *
     * @param used the value for hq_composition.used
     *
     * @mbg.generated
     */
    public void setUsed(String used) {
        this.used = used == null ? null : used.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.used_name
     *
     * @return the value of hq_composition.used_name
     *
     * @mbg.generated
     */
    public String getUsedName() {
        return usedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withUsedName(String usedName) {
        this.setUsedName(usedName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.used_name
     *
     * @param usedName the value for hq_composition.used_name
     *
     * @mbg.generated
     */
    public void setUsedName(String usedName) {
        this.usedName = usedName == null ? null : usedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.pid
     *
     * @return the value of hq_composition.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withPid(Integer pid) {
        this.setPid(pid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.pid
     *
     * @param pid the value for hq_composition.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.likecount
     *
     * @return the value of hq_composition.likecount
     *
     * @mbg.generated
     */
    public Integer getLikecount() {
        return likecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withLikecount(Integer likecount) {
        this.setLikecount(likecount);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.likecount
     *
     * @param likecount the value for hq_composition.likecount
     *
     * @mbg.generated
     */
    public void setLikecount(Integer likecount) {
        this.likecount = likecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.commentcount
     *
     * @return the value of hq_composition.commentcount
     *
     * @mbg.generated
     */
    public Integer getCommentcount() {
        return commentcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withCommentcount(Integer commentcount) {
        this.setCommentcount(commentcount);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.commentcount
     *
     * @param commentcount the value for hq_composition.commentcount
     *
     * @mbg.generated
     */
    public void setCommentcount(Integer commentcount) {
        this.commentcount = commentcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.OSPW
     *
     * @return the value of hq_composition.OSPW
     *
     * @mbg.generated
     */
    public String getOspw() {
        return ospw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withOspw(String ospw) {
        this.setOspw(ospw);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.OSPW
     *
     * @param ospw the value for hq_composition.OSPW
     *
     * @mbg.generated
     */
    public void setOspw(String ospw) {
        this.ospw = ospw == null ? null : ospw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.OSPT
     *
     * @return the value of hq_composition.OSPT
     *
     * @mbg.generated
     */
    public String getOspt() {
        return ospt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withOspt(String ospt) {
        this.setOspt(ospt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.OSPT
     *
     * @param ospt the value for hq_composition.OSPT
     *
     * @mbg.generated
     */
    public void setOspt(String ospt) {
        this.ospt = ospt == null ? null : ospt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.OSNW
     *
     * @return the value of hq_composition.OSNW
     *
     * @mbg.generated
     */
    public String getOsnw() {
        return osnw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withOsnw(String osnw) {
        this.setOsnw(osnw);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.OSNW
     *
     * @param osnw the value for hq_composition.OSNW
     *
     * @mbg.generated
     */
    public void setOsnw(String osnw) {
        this.osnw = osnw == null ? null : osnw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.OSNT
     *
     * @return the value of hq_composition.OSNT
     *
     * @mbg.generated
     */
    public String getOsnt() {
        return osnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withOsnt(String osnt) {
        this.setOsnt(osnt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.OSNT
     *
     * @param osnt the value for hq_composition.OSNT
     *
     * @mbg.generated
     */
    public void setOsnt(String osnt) {
        this.osnt = osnt == null ? null : osnt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.ORPW
     *
     * @return the value of hq_composition.ORPW
     *
     * @mbg.generated
     */
    public String getOrpw() {
        return orpw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withOrpw(String orpw) {
        this.setOrpw(orpw);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.ORPW
     *
     * @param orpw the value for hq_composition.ORPW
     *
     * @mbg.generated
     */
    public void setOrpw(String orpw) {
        this.orpw = orpw == null ? null : orpw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.ORNW
     *
     * @return the value of hq_composition.ORNW
     *
     * @mbg.generated
     */
    public String getOrnw() {
        return ornw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withOrnw(String ornw) {
        this.setOrnw(ornw);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.ORNW
     *
     * @param ornw the value for hq_composition.ORNW
     *
     * @mbg.generated
     */
    public void setOrnw(String ornw) {
        this.ornw = ornw == null ? null : ornw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.ORNT
     *
     * @return the value of hq_composition.ORNT
     *
     * @mbg.generated
     */
    public String getOrnt() {
        return ornt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withOrnt(String ornt) {
        this.setOrnt(ornt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.ORNT
     *
     * @param ornt the value for hq_composition.ORNT
     *
     * @mbg.generated
     */
    public void setOrnt(String ornt) {
        this.ornt = ornt == null ? null : ornt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.DSPW
     *
     * @return the value of hq_composition.DSPW
     *
     * @mbg.generated
     */
    public String getDspw() {
        return dspw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withDspw(String dspw) {
        this.setDspw(dspw);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.DSPW
     *
     * @param dspw the value for hq_composition.DSPW
     *
     * @mbg.generated
     */
    public void setDspw(String dspw) {
        this.dspw = dspw == null ? null : dspw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.DSPT
     *
     * @return the value of hq_composition.DSPT
     *
     * @mbg.generated
     */
    public String getDspt() {
        return dspt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withDspt(String dspt) {
        this.setDspt(dspt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.DSPT
     *
     * @param dspt the value for hq_composition.DSPT
     *
     * @mbg.generated
     */
    public void setDspt(String dspt) {
        this.dspt = dspt == null ? null : dspt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.DSNW
     *
     * @return the value of hq_composition.DSNW
     *
     * @mbg.generated
     */
    public String getDsnw() {
        return dsnw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withDsnw(String dsnw) {
        this.setDsnw(dsnw);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.DSNW
     *
     * @param dsnw the value for hq_composition.DSNW
     *
     * @mbg.generated
     */
    public void setDsnw(String dsnw) {
        this.dsnw = dsnw == null ? null : dsnw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.DSNT
     *
     * @return the value of hq_composition.DSNT
     *
     * @mbg.generated
     */
    public String getDsnt() {
        return dsnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withDsnt(String dsnt) {
        this.setDsnt(dsnt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.DSNT
     *
     * @param dsnt the value for hq_composition.DSNT
     *
     * @mbg.generated
     */
    public void setDsnt(String dsnt) {
        this.dsnt = dsnt == null ? null : dsnt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.DRPW
     *
     * @return the value of hq_composition.DRPW
     *
     * @mbg.generated
     */
    public String getDrpw() {
        return drpw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withDrpw(String drpw) {
        this.setDrpw(drpw);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.DRPW
     *
     * @param drpw the value for hq_composition.DRPW
     *
     * @mbg.generated
     */
    public void setDrpw(String drpw) {
        this.drpw = drpw == null ? null : drpw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.DRPT
     *
     * @return the value of hq_composition.DRPT
     *
     * @mbg.generated
     */
    public String getDrpt() {
        return drpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withDrpt(String drpt) {
        this.setDrpt(drpt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.DRPT
     *
     * @param drpt the value for hq_composition.DRPT
     *
     * @mbg.generated
     */
    public void setDrpt(String drpt) {
        this.drpt = drpt == null ? null : drpt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.DRNW
     *
     * @return the value of hq_composition.DRNW
     *
     * @mbg.generated
     */
    public String getDrnw() {
        return drnw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withDrnw(String drnw) {
        this.setDrnw(drnw);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.DRNW
     *
     * @param drnw the value for hq_composition.DRNW
     *
     * @mbg.generated
     */
    public void setDrnw(String drnw) {
        this.drnw = drnw == null ? null : drnw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.DRNT
     *
     * @return the value of hq_composition.DRNT
     *
     * @mbg.generated
     */
    public String getDrnt() {
        return drnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withDrnt(String drnt) {
        this.setDrnt(drnt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.DRNT
     *
     * @param drnt the value for hq_composition.DRNT
     *
     * @mbg.generated
     */
    public void setDrnt(String drnt) {
        this.drnt = drnt == null ? null : drnt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.ORPT
     *
     * @return the value of hq_composition.ORPT
     *
     * @mbg.generated
     */
    public String getOrpt() {
        return orpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withOrpt(String orpt) {
        this.setOrpt(orpt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.ORPT
     *
     * @param orpt the value for hq_composition.ORPT
     *
     * @mbg.generated
     */
    public void setOrpt(String orpt) {
        this.orpt = orpt == null ? null : orpt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.mid
     *
     * @return the value of hq_composition.mid
     *
     * @mbg.generated
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withMid(String mid) {
        this.setMid(mid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.mid
     *
     * @param mid the value for hq_composition.mid
     *
     * @mbg.generated
     */
    public void setMid(String mid) {
        this.mid = mid == null ? null : mid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.mpid
     *
     * @return the value of hq_composition.mpid
     *
     * @mbg.generated
     */
    public String getMpid() {
        return mpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withMpid(String mpid) {
        this.setMpid(mpid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.mpid
     *
     * @param mpid the value for hq_composition.mpid
     *
     * @mbg.generated
     */
    public void setMpid(String mpid) {
        this.mpid = mpid == null ? null : mpid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.namelength
     *
     * @return the value of hq_composition.namelength
     *
     * @mbg.generated
     */
    public Integer getNamelength() {
        return namelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withNamelength(Integer namelength) {
        this.setNamelength(namelength);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.namelength
     *
     * @param namelength the value for hq_composition.namelength
     *
     * @mbg.generated
     */
    public void setNamelength(Integer namelength) {
        this.namelength = namelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.u1
     *
     * @return the value of hq_composition.u1
     *
     * @mbg.generated
     */
    public Integer getU1() {
        return u1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withU1(Integer u1) {
        this.setU1(u1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.u1
     *
     * @param u1 the value for hq_composition.u1
     *
     * @mbg.generated
     */
    public void setU1(Integer u1) {
        this.u1 = u1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.reserve
     *
     * @return the value of hq_composition.reserve
     *
     * @mbg.generated
     */
    public Integer getReserve() {
        return reserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withReserve(Integer reserve) {
        this.setReserve(reserve);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.reserve
     *
     * @param reserve the value for hq_composition.reserve
     *
     * @mbg.generated
     */
    public void setReserve(Integer reserve) {
        this.reserve = reserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.cm_name
     *
     * @return the value of hq_composition.cm_name
     *
     * @mbg.generated
     */
    public String getCmName() {
        return cmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withCmName(String cmName) {
        this.setCmName(cmName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.cm_name
     *
     * @param cmName the value for hq_composition.cm_name
     *
     * @mbg.generated
     */
    public void setCmName(String cmName) {
        this.cmName = cmName == null ? null : cmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_composition.cm_english
     *
     * @return the value of hq_composition.cm_english
     *
     * @mbg.generated
     */
    public String getCmEnglish() {
        return cmEnglish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_composition
     *
     * @mbg.generated
     */
    public Composition withCmEnglish(String cmEnglish) {
        this.setCmEnglish(cmEnglish);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_composition.cm_english
     *
     * @param cmEnglish the value for hq_composition.cm_english
     *
     * @mbg.generated
     */
    public void setCmEnglish(String cmEnglish) {
        this.cmEnglish = cmEnglish == null ? null : cmEnglish.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table hq_composition
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        tstamp("tstamp"),
        crdate("crdate"),
        cruserId("cruser_id"),
        deleted("deleted"),
        hidden("hidden"),
        sorting("sorting"),
        hit("hit"),
        hot("hot"),
        top("top"),
        name("name"),
        efficacy("efficacy"),
        english("english"),
        frequency("frequency"),
        active("active"),
        safety("safety"),
        acneRisk("acne_risk"),
        cas("cas"),
        otherTitle("other_title"),
        usedNum("used_num"),
        shenyong("shenyong"),
        used("used"),
        usedName("used_name"),
        pid("pid"),
        likecount("likecount"),
        commentcount("commentcount"),
        ospw("OSPW"),
        ospt("OSPT"),
        osnw("OSNW"),
        osnt("OSNT"),
        orpw("ORPW"),
        ornw("ORNW"),
        ornt("ORNT"),
        dspw("DSPW"),
        dspt("DSPT"),
        dsnw("DSNW"),
        dsnt("DSNT"),
        drpw("DRPW"),
        drpt("DRPT"),
        drnw("DRNW"),
        drnt("DRNT"),
        orpt("ORPT"),
        mid("mid"),
        mpid("mpid"),
        namelength("namelength"),
        u1("u1"),
        reserve("reserve"),
        cmName("cm_name"),
        cmEnglish("cm_english"),
        remark("remark"),
        namejp("namejp");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hq_composition
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_composition
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_composition
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_composition
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_composition
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_composition
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}