package cn.bevol.statics.dao;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hq_goods_ext
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class GoodsExt implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_ext.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_ext.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     * Database Column Remarks:
     *   是否允许发送产品评论 1:禁止  0：允许
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_ext.allow_comment
     *
     * @mbg.generated
     */
    private Boolean allowComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_ext.id
     *
     * @return the value of hq_goods_ext.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     */
    public GoodsExt withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_ext.id
     *
     * @param id the value for hq_goods_ext.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_ext.goods_id
     *
     * @return the value of hq_goods_ext.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     */
    public GoodsExt withGoodsId(Integer goodsId) {
        this.setGoodsId(goodsId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_ext.goods_id
     *
     * @param goodsId the value for hq_goods_ext.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_ext.allow_comment
     *
     * @return the value of hq_goods_ext.allow_comment
     *
     * @mbg.generated
     */
    public Boolean getAllowComment() {
        return allowComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     */
    public GoodsExt withAllowComment(Boolean allowComment) {
        this.setAllowComment(allowComment);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_ext.allow_comment
     *
     * @param allowComment the value for hq_goods_ext.allow_comment
     *
     * @mbg.generated
     */
    public void setAllowComment(Boolean allowComment) {
        this.allowComment = allowComment;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        goodsId("goods_id"),
        allowComment("allow_comment"),
        defCps("def_cps"),
        gcCps("gc_cps"),
        mfjCps("mfj_cps"),
        defExtCps("def_ext_cps"),
        cpsType("cps_type"),
        cps("cps");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hq_goods_ext
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_ext
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_ext
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_ext
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_ext
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_ext
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}