package cn.bevol.statics.dao;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hq_goods_tag_composition
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class GoodsTagComposition implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_composition.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_composition.tag_id
     *
     * @mbg.generated
     */
    private Integer tagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_composition.composition_id
     *
     * @mbg.generated
     */
    private Integer compositionId;

    /**
     * Database Column Remarks:
     *   不含有的成分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_composition.not_composition_id
     *
     * @mbg.generated
     */
    private Integer notCompositionId;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_composition.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_composition.create_stamp
     *
     * @mbg.generated
     */
    private Integer createStamp;

    /**
     * Database Column Remarks:
     *   1表示核心成分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_composition.is_main
     *
     * @mbg.generated
     */
    private Boolean isMain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_composition.main_name
     *
     * @mbg.generated
     */
    private String mainName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_composition.id
     *
     * @return the value of hq_goods_tag_composition.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     */
    public GoodsTagComposition withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_composition.id
     *
     * @param id the value for hq_goods_tag_composition.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_composition.tag_id
     *
     * @return the value of hq_goods_tag_composition.tag_id
     *
     * @mbg.generated
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     */
    public GoodsTagComposition withTagId(Integer tagId) {
        this.setTagId(tagId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_composition.tag_id
     *
     * @param tagId the value for hq_goods_tag_composition.tag_id
     *
     * @mbg.generated
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_composition.composition_id
     *
     * @return the value of hq_goods_tag_composition.composition_id
     *
     * @mbg.generated
     */
    public Integer getCompositionId() {
        return compositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     */
    public GoodsTagComposition withCompositionId(Integer compositionId) {
        this.setCompositionId(compositionId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_composition.composition_id
     *
     * @param compositionId the value for hq_goods_tag_composition.composition_id
     *
     * @mbg.generated
     */
    public void setCompositionId(Integer compositionId) {
        this.compositionId = compositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_composition.not_composition_id
     *
     * @return the value of hq_goods_tag_composition.not_composition_id
     *
     * @mbg.generated
     */
    public Integer getNotCompositionId() {
        return notCompositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     */
    public GoodsTagComposition withNotCompositionId(Integer notCompositionId) {
        this.setNotCompositionId(notCompositionId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_composition.not_composition_id
     *
     * @param notCompositionId the value for hq_goods_tag_composition.not_composition_id
     *
     * @mbg.generated
     */
    public void setNotCompositionId(Integer notCompositionId) {
        this.notCompositionId = notCompositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_composition.status
     *
     * @return the value of hq_goods_tag_composition.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     */
    public GoodsTagComposition withStatus(Boolean status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_composition.status
     *
     * @param status the value for hq_goods_tag_composition.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_composition.create_stamp
     *
     * @return the value of hq_goods_tag_composition.create_stamp
     *
     * @mbg.generated
     */
    public Integer getCreateStamp() {
        return createStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     */
    public GoodsTagComposition withCreateStamp(Integer createStamp) {
        this.setCreateStamp(createStamp);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_composition.create_stamp
     *
     * @param createStamp the value for hq_goods_tag_composition.create_stamp
     *
     * @mbg.generated
     */
    public void setCreateStamp(Integer createStamp) {
        this.createStamp = createStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_composition.is_main
     *
     * @return the value of hq_goods_tag_composition.is_main
     *
     * @mbg.generated
     */
    public Boolean getIsMain() {
        return isMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     */
    public GoodsTagComposition withIsMain(Boolean isMain) {
        this.setIsMain(isMain);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_composition.is_main
     *
     * @param isMain the value for hq_goods_tag_composition.is_main
     *
     * @mbg.generated
     */
    public void setIsMain(Boolean isMain) {
        this.isMain = isMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_composition.main_name
     *
     * @return the value of hq_goods_tag_composition.main_name
     *
     * @mbg.generated
     */
    public String getMainName() {
        return mainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     */
    public GoodsTagComposition withMainName(String mainName) {
        this.setMainName(mainName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_composition.main_name
     *
     * @param mainName the value for hq_goods_tag_composition.main_name
     *
     * @mbg.generated
     */
    public void setMainName(String mainName) {
        this.mainName = mainName == null ? null : mainName.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        tagId("tag_id"),
        compositionId("composition_id"),
        notCompositionId("not_composition_id"),
        status("status"),
        createStamp("create_stamp"),
        isMain("is_main"),
        mainName("main_name");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hq_goods_tag_composition
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_tag_composition
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_tag_composition
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_tag_composition
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_tag_composition
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_tag_composition
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}