package cn.bevol.statics.dao;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hq_goods_tag_rule
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class GoodsTagRule implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_rule.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   规则json
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_rule.val_json
     *
     * @mbg.generated
     */
    private String valJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_rule.create_stamp
     *
     * @mbg.generated
     */
    private Integer createStamp;

    /**
     * Database Column Remarks:
     *   状态 0为显示 1为隐藏
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_rule.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * Database Column Remarks:
     *   标签id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_rule.tag_id
     *
     * @mbg.generated
     */
    private Integer tagId;

    /**
     * Database Column Remarks:
     *   产品名包含的字符
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_rule.rule_1
     *
     * @mbg.generated
     */
    private String rule1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_rule.id
     *
     * @return the value of hq_goods_tag_rule.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     */
    public GoodsTagRule withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_rule.id
     *
     * @param id the value for hq_goods_tag_rule.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_rule.val_json
     *
     * @return the value of hq_goods_tag_rule.val_json
     *
     * @mbg.generated
     */
    public String getValJson() {
        return valJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     */
    public GoodsTagRule withValJson(String valJson) {
        this.setValJson(valJson);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_rule.val_json
     *
     * @param valJson the value for hq_goods_tag_rule.val_json
     *
     * @mbg.generated
     */
    public void setValJson(String valJson) {
        this.valJson = valJson == null ? null : valJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_rule.create_stamp
     *
     * @return the value of hq_goods_tag_rule.create_stamp
     *
     * @mbg.generated
     */
    public Integer getCreateStamp() {
        return createStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     */
    public GoodsTagRule withCreateStamp(Integer createStamp) {
        this.setCreateStamp(createStamp);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_rule.create_stamp
     *
     * @param createStamp the value for hq_goods_tag_rule.create_stamp
     *
     * @mbg.generated
     */
    public void setCreateStamp(Integer createStamp) {
        this.createStamp = createStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_rule.status
     *
     * @return the value of hq_goods_tag_rule.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     */
    public GoodsTagRule withStatus(Boolean status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_rule.status
     *
     * @param status the value for hq_goods_tag_rule.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_rule.tag_id
     *
     * @return the value of hq_goods_tag_rule.tag_id
     *
     * @mbg.generated
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     */
    public GoodsTagRule withTagId(Integer tagId) {
        this.setTagId(tagId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_rule.tag_id
     *
     * @param tagId the value for hq_goods_tag_rule.tag_id
     *
     * @mbg.generated
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_rule.rule_1
     *
     * @return the value of hq_goods_tag_rule.rule_1
     *
     * @mbg.generated
     */
    public String getRule1() {
        return rule1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     */
    public GoodsTagRule withRule1(String rule1) {
        this.setRule1(rule1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_rule.rule_1
     *
     * @param rule1 the value for hq_goods_tag_rule.rule_1
     *
     * @mbg.generated
     */
    public void setRule1(String rule1) {
        this.rule1 = rule1 == null ? null : rule1.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        valJson("val_json"),
        createStamp("create_stamp"),
        status("status"),
        tagId("tag_id"),
        rule1("rule_1");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hq_goods_tag_rule
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_tag_rule
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_tag_rule
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_tag_rule
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_tag_rule
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_tag_rule
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}