package cn.bevol.app.dao.mapper;

import cn.bevol.app.dao.DirtyComposition;
import cn.bevol.app.dao.DirtyCompositionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DirtyCompositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     */
    long countByExample(DirtyCompositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     */
    int insert(DirtyComposition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     */
    int insertSelective(DirtyComposition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     */
    List<DirtyComposition> selectByExampleWithRowbounds(DirtyCompositionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     */
    List<DirtyComposition> selectByExample(DirtyCompositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     */
    DirtyComposition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DirtyComposition record, @Param("example") DirtyCompositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DirtyComposition record, @Param("example") DirtyCompositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DirtyComposition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DirtyComposition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<DirtyComposition> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<DirtyComposition> list, @Param("selective") DirtyComposition.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DirtyComposition selectOneByExample(DirtyCompositionExample example);
}