package cn.bevol.internal.dao;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hq_goods_ext
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ConfigWithBLOBs extends Config {
    /**
     * Database Column Remarks:
     *   药监局顺序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_ext.def_cps
     *
     * @mbg.generated
     */
    private String defCps;

    /**
     * Database Column Remarks:
     *   手动排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_ext.gc_cps
     *
     * @mbg.generated
     */
    private String gcCps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_ext.mfj_cps
     *
     * @mbg.generated
     */
    private String mfjCps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_ext.def_ext_cps
     *
     * @mbg.generated
     */
    private String defExtCps;

    /**
     * Database Column Remarks:
     *   默认def_cps
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_ext.cps_type
     *
     * @mbg.generated
     */
    private String cpsType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_ext.def_cps
     *
     * @return the value of hq_goods_ext.def_cps
     *
     * @mbg.generated
     */
    public String getDefCps() {
        return defCps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_ext.def_cps
     *
     * @param defCps the value for hq_goods_ext.def_cps
     *
     * @mbg.generated
     */
    public void setDefCps(String defCps) {
        this.defCps = defCps == null ? null : defCps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_ext.gc_cps
     *
     * @return the value of hq_goods_ext.gc_cps
     *
     * @mbg.generated
     */
    public String getGcCps() {
        return gcCps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_ext.gc_cps
     *
     * @param gcCps the value for hq_goods_ext.gc_cps
     *
     * @mbg.generated
     */
    public void setGcCps(String gcCps) {
        this.gcCps = gcCps == null ? null : gcCps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_ext.mfj_cps
     *
     * @return the value of hq_goods_ext.mfj_cps
     *
     * @mbg.generated
     */
    public String getMfjCps() {
        return mfjCps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_ext.mfj_cps
     *
     * @param mfjCps the value for hq_goods_ext.mfj_cps
     *
     * @mbg.generated
     */
    public void setMfjCps(String mfjCps) {
        this.mfjCps = mfjCps == null ? null : mfjCps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_ext.def_ext_cps
     *
     * @return the value of hq_goods_ext.def_ext_cps
     *
     * @mbg.generated
     */
    public String getDefExtCps() {
        return defExtCps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_ext.def_ext_cps
     *
     * @param defExtCps the value for hq_goods_ext.def_ext_cps
     *
     * @mbg.generated
     */
    public void setDefExtCps(String defExtCps) {
        this.defExtCps = defExtCps == null ? null : defExtCps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_ext.cps_type
     *
     * @return the value of hq_goods_ext.cps_type
     *
     * @mbg.generated
     */
    public String getCpsType() {
        return cpsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_ext.cps_type
     *
     * @param cpsType the value for hq_goods_ext.cps_type
     *
     * @mbg.generated
     */
    public void setCpsType(String cpsType) {
        this.cpsType = cpsType == null ? null : cpsType.trim();
    }
}