package cn.bevol.internal.dao;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hq_dirty_composition
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class DirtyComposition implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_dirty_composition.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_dirty_composition.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   对应hq_composition里的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_dirty_composition.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_dirty_composition.crdate
     *
     * @mbg.generated
     */
    private Date crdate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_dirty_composition.tstamp
     *
     * @mbg.generated
     */
    private Date tstamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_dirty_composition.delete_status
     *
     * @mbg.generated
     */
    private Integer deleteStatus;

    /**
     * Database Column Remarks:
     *   是否是别名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_dirty_composition.alias
     *
     * @mbg.generated
     */
    private Integer alias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_dirty_composition.cm_name
     *
     * @mbg.generated
     */
    private String cmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_dirty_composition.id
     *
     * @return the value of hq_dirty_composition.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     */
    public DirtyComposition withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_dirty_composition.id
     *
     * @param id the value for hq_dirty_composition.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_dirty_composition.name
     *
     * @return the value of hq_dirty_composition.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     */
    public DirtyComposition withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_dirty_composition.name
     *
     * @param name the value for hq_dirty_composition.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_dirty_composition.pid
     *
     * @return the value of hq_dirty_composition.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     */
    public DirtyComposition withPid(Integer pid) {
        this.setPid(pid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_dirty_composition.pid
     *
     * @param pid the value for hq_dirty_composition.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_dirty_composition.crdate
     *
     * @return the value of hq_dirty_composition.crdate
     *
     * @mbg.generated
     */
    public Date getCrdate() {
        return crdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     */
    public DirtyComposition withCrdate(Date crdate) {
        this.setCrdate(crdate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_dirty_composition.crdate
     *
     * @param crdate the value for hq_dirty_composition.crdate
     *
     * @mbg.generated
     */
    public void setCrdate(Date crdate) {
        this.crdate = crdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_dirty_composition.tstamp
     *
     * @return the value of hq_dirty_composition.tstamp
     *
     * @mbg.generated
     */
    public Date getTstamp() {
        return tstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     */
    public DirtyComposition withTstamp(Date tstamp) {
        this.setTstamp(tstamp);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_dirty_composition.tstamp
     *
     * @param tstamp the value for hq_dirty_composition.tstamp
     *
     * @mbg.generated
     */
    public void setTstamp(Date tstamp) {
        this.tstamp = tstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_dirty_composition.delete_status
     *
     * @return the value of hq_dirty_composition.delete_status
     *
     * @mbg.generated
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     */
    public DirtyComposition withDeleteStatus(Integer deleteStatus) {
        this.setDeleteStatus(deleteStatus);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_dirty_composition.delete_status
     *
     * @param deleteStatus the value for hq_dirty_composition.delete_status
     *
     * @mbg.generated
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_dirty_composition.alias
     *
     * @return the value of hq_dirty_composition.alias
     *
     * @mbg.generated
     */
    public Integer getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     */
    public DirtyComposition withAlias(Integer alias) {
        this.setAlias(alias);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_dirty_composition.alias
     *
     * @param alias the value for hq_dirty_composition.alias
     *
     * @mbg.generated
     */
    public void setAlias(Integer alias) {
        this.alias = alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_dirty_composition.cm_name
     *
     * @return the value of hq_dirty_composition.cm_name
     *
     * @mbg.generated
     */
    public String getCmName() {
        return cmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     */
    public DirtyComposition withCmName(String cmName) {
        this.setCmName(cmName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_dirty_composition.cm_name
     *
     * @param cmName the value for hq_dirty_composition.cm_name
     *
     * @mbg.generated
     */
    public void setCmName(String cmName) {
        this.cmName = cmName == null ? null : cmName.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table hq_dirty_composition
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        name("name"),
        pid("pid"),
        crdate("crdate"),
        tstamp("tstamp"),
        deleteStatus("delete_status"),
        alias("alias"),
        cmName("cm_name");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hq_dirty_composition
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_dirty_composition
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_dirty_composition
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_dirty_composition
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_dirty_composition
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_dirty_composition
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}