package cn.bevol.internal.dao;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hq_goods
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Goods implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.brand_id
     *
     * @mbg.generated
     */
    private Integer brandId;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.tstamp
     *
     * @mbg.generated
     */
    private Integer tstamp;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.crdate
     *
     * @mbg.generated
     */
    private Integer crdate;

    /**
     * Database Column Remarks:
     *   活动开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.startdate
     *
     * @mbg.generated
     */
    private Integer startdate;

    /**
     * Database Column Remarks:
     *   活动结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.overdate
     *
     * @mbg.generated
     */
    private Integer overdate;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.cruser_id
     *
     * @mbg.generated
     */
    private Integer cruserId;

    /**
     * Database Column Remarks:
     *   删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.deleted
     *
     * @mbg.generated
     */
    private Integer deleted;

    /**
     * Database Column Remarks:
     *   隐藏
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.hidden
     *
     * @mbg.generated
     */
    private Integer hidden;

    /**
     * Database Column Remarks:
     *   合并后的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.merge_id
     *
     * @mbg.generated
     */
    private Integer mergeId;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.sorting
     *
     * @mbg.generated
     */
    private Float sorting;

    /**
     * Database Column Remarks:
     *   访问次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.hit
     *
     * @mbg.generated
     */
    private Integer hit;

    /**
     * Database Column Remarks:
     *   推荐
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.hot
     *
     * @mbg.generated
     */
    private Integer hot;

    /**
     * Database Column Remarks:
     *   置顶
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.top
     *
     * @mbg.generated
     */
    private Integer top;

    /**
     * Database Column Remarks:
     *   产品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   中文拼音
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.alias
     *
     * @mbg.generated
     */
    private String alias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.alias_2
     *
     * @mbg.generated
     */
    private String alias2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.image
     *
     * @mbg.generated
     */
    private String image;

    /**
     * Database Column Remarks:
     *   所属分类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.category
     *
     * @mbg.generated
     */
    private Integer category;

    /**
     * Database Column Remarks:
     *   生产企业
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.company
     *
     * @mbg.generated
     */
    private String company;

    /**
     * Database Column Remarks:
     *   生产企业英文
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.company_english
     *
     * @mbg.generated
     */
    private String companyEnglish;

    /**
     * Database Column Remarks:
     *   生产企业地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   批准/备案文号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.approval
     *
     * @mbg.generated
     */
    private String approval;

    /**
     * Database Column Remarks:
     *   批件状态 0 当前批件 1 历史批件 2 已过期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * Database Column Remarks:
     *   批准/备案日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.approval_date
     *
     * @mbg.generated
     */
    private Integer approvalDate;

    /**
     * Database Column Remarks:
     *   批件有效期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.validity_date
     *
     * @mbg.generated
     */
    private String validityDate;

    /**
     * Database Column Remarks:
     *   许可证
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.license
     *
     * @mbg.generated
     */
    private String license;

    /**
     * Database Column Remarks:
     *   产品名称备注 别名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.remark3
     *
     * @mbg.generated
     */
    private String remark3;

    /**
     * Database Column Remarks:
     *   产品技术要求
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.skills
     *
     * @mbg.generated
     */
    private String skills;

    /**
     * Database Column Remarks:
     *   产品关键词
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.keywords
     *
     * @mbg.generated
     */
    private String keywords;

    /**
     * Database Column Remarks:
     *   喜欢人数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.like_num
     *
     * @mbg.generated
     */
    private Integer likeNum;

    /**
     * Database Column Remarks:
     *   使用人数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.used_num
     *
     * @mbg.generated
     */
    private Integer usedNum;

    /**
     * Database Column Remarks:
     *   来源
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.fromz
     *
     * @mbg.generated
     */
    private String fromz;

    /**
     * Database Column Remarks:
     *   是否有成分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.flag
     *
     * @mbg.generated
     */
    private Boolean flag;

    /**
     * Database Column Remarks:
     *   备案号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.record_num
     *
     * @mbg.generated
     */
    private String recordNum;

    /**
     * Database Column Remarks:
     *   备案日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.record_date
     *
     * @mbg.generated
     */
    private Integer recordDate;

    /**
     * Database Column Remarks:
     *   有无备案 0 未备案 1 已备案
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.is_record
     *
     * @mbg.generated
     */
    private Boolean isRecord;

    /**
     * Database Column Remarks:
     *   实际生产企业名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.actual_company
     *
     * @mbg.generated
     */
    private String actualCompany;

    /**
     * Database Column Remarks:
     *   实际生产企业地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.actual_company_address
     *
     * @mbg.generated
     */
    private String actualCompanyAddress;

    /**
     * Database Column Remarks:
     *   数据来源 1 进口库 2 国产特殊 3 国产普通 4 产品标签
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.data_type
     *
     * @mbg.generated
     */
    private Integer dataType;

    /**
     * Database Column Remarks:
     *   在华申报责任单位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.china_company
     *
     * @mbg.generated
     */
    private String chinaCompany;

    /**
     * Database Column Remarks:
     *   在华责任单位地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.china_address
     *
     * @mbg.generated
     */
    private String chinaAddress;

    /**
     * Database Column Remarks:
     *   生产国家
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     * Database Column Remarks:
     *   国产普通说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.instruction
     *
     * @mbg.generated
     */
    private String instruction;

    /**
     * Database Column Remarks:
     *   品牌名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.brand
     *
     * @mbg.generated
     */
    private String brand;

    /**
     * Database Column Remarks:
     *   类型  （临时字段）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.cname
     *
     * @mbg.generated
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.processid
     *
     * @mbg.generated
     */
    private String processid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.ishas
     *
     * @mbg.generated
     */
    private Boolean ishas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.iscag
     *
     * @mbg.generated
     */
    private Boolean iscag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.skillsUrl
     *
     * @mbg.generated
     */
    private String skillsurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.categoryStr
     *
     * @mbg.generated
     */
    private String categorystr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.likecount
     *
     * @mbg.generated
     */
    private Integer likecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.commentcount
     *
     * @mbg.generated
     */
    private Integer commentcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.notlikecount
     *
     * @mbg.generated
     */
    private Integer notlikecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.mid
     *
     * @mbg.generated
     */
    private String mid;

    /**
     * Database Column Remarks:
     *   0未修改
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.ismodify
     *
     * @mbg.generated
     */
    private Boolean ismodify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.new_goods_title
     *
     * @mbg.generated
     */
    private String newGoodsTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.doyenid
     *
     * @mbg.generated
     */
    private Integer doyenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.isdoyenmodify
     *
     * @mbg.generated
     */
    private Integer isdoyenmodify;

    /**
     * Database Column Remarks:
     *   参考价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.price
     *
     * @mbg.generated
     */
    private String price;

    /**
     * Database Column Remarks:
     *   参考价格对应的容量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.capacity
     *
     * @mbg.generated
     */
    private String capacity;

    /**
     * Database Column Remarks:
     *   售价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.sell_price
     *
     * @mbg.generated
     */
    private BigDecimal sellPrice;

    /**
     * Database Column Remarks:
     *   售价对应容量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.sell_capacity
     *
     * @mbg.generated
     */
    private String sellCapacity;

    /**
     * Database Column Remarks:
     *   微商=10
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.hidden_skin
     *
     * @mbg.generated
     */
    private Integer hiddenSkin;

    /**
     * Database Column Remarks:
     *   'def_cps_1':'产品配方顺序','cps_def_2':'产品配方顺序','def_cps_3':'产品备案顺序','gc_cps':'标签顺序','mfj_cps':'标签顺序','def':'标签顺序','def_ext_cps:''标签顺序'
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.cps_type
     *
     * @mbg.generated
     */
    private String cpsType;

    /**
     * Database Column Remarks:
     *   1:人民币；2：美元
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods.price_unit
     *
     * @mbg.generated
     */
    private Integer priceUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.id
     *
     * @return the value of hq_goods.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.id
     *
     * @param id the value for hq_goods.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.brand_id
     *
     * @return the value of hq_goods.brand_id
     *
     * @mbg.generated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withBrandId(Integer brandId) {
        this.setBrandId(brandId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.brand_id
     *
     * @param brandId the value for hq_goods.brand_id
     *
     * @mbg.generated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.tstamp
     *
     * @return the value of hq_goods.tstamp
     *
     * @mbg.generated
     */
    public Integer getTstamp() {
        return tstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withTstamp(Integer tstamp) {
        this.setTstamp(tstamp);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.tstamp
     *
     * @param tstamp the value for hq_goods.tstamp
     *
     * @mbg.generated
     */
    public void setTstamp(Integer tstamp) {
        this.tstamp = tstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.crdate
     *
     * @return the value of hq_goods.crdate
     *
     * @mbg.generated
     */
    public Integer getCrdate() {
        return crdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withCrdate(Integer crdate) {
        this.setCrdate(crdate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.crdate
     *
     * @param crdate the value for hq_goods.crdate
     *
     * @mbg.generated
     */
    public void setCrdate(Integer crdate) {
        this.crdate = crdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.startdate
     *
     * @return the value of hq_goods.startdate
     *
     * @mbg.generated
     */
    public Integer getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withStartdate(Integer startdate) {
        this.setStartdate(startdate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.startdate
     *
     * @param startdate the value for hq_goods.startdate
     *
     * @mbg.generated
     */
    public void setStartdate(Integer startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.overdate
     *
     * @return the value of hq_goods.overdate
     *
     * @mbg.generated
     */
    public Integer getOverdate() {
        return overdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withOverdate(Integer overdate) {
        this.setOverdate(overdate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.overdate
     *
     * @param overdate the value for hq_goods.overdate
     *
     * @mbg.generated
     */
    public void setOverdate(Integer overdate) {
        this.overdate = overdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.cruser_id
     *
     * @return the value of hq_goods.cruser_id
     *
     * @mbg.generated
     */
    public Integer getCruserId() {
        return cruserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withCruserId(Integer cruserId) {
        this.setCruserId(cruserId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.cruser_id
     *
     * @param cruserId the value for hq_goods.cruser_id
     *
     * @mbg.generated
     */
    public void setCruserId(Integer cruserId) {
        this.cruserId = cruserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.deleted
     *
     * @return the value of hq_goods.deleted
     *
     * @mbg.generated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withDeleted(Integer deleted) {
        this.setDeleted(deleted);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.deleted
     *
     * @param deleted the value for hq_goods.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.hidden
     *
     * @return the value of hq_goods.hidden
     *
     * @mbg.generated
     */
    public Integer getHidden() {
        return hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withHidden(Integer hidden) {
        this.setHidden(hidden);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.hidden
     *
     * @param hidden the value for hq_goods.hidden
     *
     * @mbg.generated
     */
    public void setHidden(Integer hidden) {
        this.hidden = hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.merge_id
     *
     * @return the value of hq_goods.merge_id
     *
     * @mbg.generated
     */
    public Integer getMergeId() {
        return mergeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withMergeId(Integer mergeId) {
        this.setMergeId(mergeId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.merge_id
     *
     * @param mergeId the value for hq_goods.merge_id
     *
     * @mbg.generated
     */
    public void setMergeId(Integer mergeId) {
        this.mergeId = mergeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.sorting
     *
     * @return the value of hq_goods.sorting
     *
     * @mbg.generated
     */
    public Float getSorting() {
        return sorting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withSorting(Float sorting) {
        this.setSorting(sorting);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.sorting
     *
     * @param sorting the value for hq_goods.sorting
     *
     * @mbg.generated
     */
    public void setSorting(Float sorting) {
        this.sorting = sorting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.hit
     *
     * @return the value of hq_goods.hit
     *
     * @mbg.generated
     */
    public Integer getHit() {
        return hit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withHit(Integer hit) {
        this.setHit(hit);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.hit
     *
     * @param hit the value for hq_goods.hit
     *
     * @mbg.generated
     */
    public void setHit(Integer hit) {
        this.hit = hit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.hot
     *
     * @return the value of hq_goods.hot
     *
     * @mbg.generated
     */
    public Integer getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withHot(Integer hot) {
        this.setHot(hot);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.hot
     *
     * @param hot the value for hq_goods.hot
     *
     * @mbg.generated
     */
    public void setHot(Integer hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.top
     *
     * @return the value of hq_goods.top
     *
     * @mbg.generated
     */
    public Integer getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withTop(Integer top) {
        this.setTop(top);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.top
     *
     * @param top the value for hq_goods.top
     *
     * @mbg.generated
     */
    public void setTop(Integer top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.title
     *
     * @return the value of hq_goods.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withTitle(String title) {
        this.setTitle(title);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.title
     *
     * @param title the value for hq_goods.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.alias
     *
     * @return the value of hq_goods.alias
     *
     * @mbg.generated
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withAlias(String alias) {
        this.setAlias(alias);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.alias
     *
     * @param alias the value for hq_goods.alias
     *
     * @mbg.generated
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.alias_2
     *
     * @return the value of hq_goods.alias_2
     *
     * @mbg.generated
     */
    public String getAlias2() {
        return alias2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withAlias2(String alias2) {
        this.setAlias2(alias2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.alias_2
     *
     * @param alias2 the value for hq_goods.alias_2
     *
     * @mbg.generated
     */
    public void setAlias2(String alias2) {
        this.alias2 = alias2 == null ? null : alias2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.image
     *
     * @return the value of hq_goods.image
     *
     * @mbg.generated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withImage(String image) {
        this.setImage(image);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.image
     *
     * @param image the value for hq_goods.image
     *
     * @mbg.generated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.category
     *
     * @return the value of hq_goods.category
     *
     * @mbg.generated
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withCategory(Integer category) {
        this.setCategory(category);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.category
     *
     * @param category the value for hq_goods.category
     *
     * @mbg.generated
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.company
     *
     * @return the value of hq_goods.company
     *
     * @mbg.generated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withCompany(String company) {
        this.setCompany(company);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.company
     *
     * @param company the value for hq_goods.company
     *
     * @mbg.generated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.company_english
     *
     * @return the value of hq_goods.company_english
     *
     * @mbg.generated
     */
    public String getCompanyEnglish() {
        return companyEnglish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withCompanyEnglish(String companyEnglish) {
        this.setCompanyEnglish(companyEnglish);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.company_english
     *
     * @param companyEnglish the value for hq_goods.company_english
     *
     * @mbg.generated
     */
    public void setCompanyEnglish(String companyEnglish) {
        this.companyEnglish = companyEnglish == null ? null : companyEnglish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.address
     *
     * @return the value of hq_goods.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withAddress(String address) {
        this.setAddress(address);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.address
     *
     * @param address the value for hq_goods.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.approval
     *
     * @return the value of hq_goods.approval
     *
     * @mbg.generated
     */
    public String getApproval() {
        return approval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withApproval(String approval) {
        this.setApproval(approval);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.approval
     *
     * @param approval the value for hq_goods.approval
     *
     * @mbg.generated
     */
    public void setApproval(String approval) {
        this.approval = approval == null ? null : approval.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.state
     *
     * @return the value of hq_goods.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withState(Integer state) {
        this.setState(state);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.state
     *
     * @param state the value for hq_goods.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.approval_date
     *
     * @return the value of hq_goods.approval_date
     *
     * @mbg.generated
     */
    public Integer getApprovalDate() {
        return approvalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withApprovalDate(Integer approvalDate) {
        this.setApprovalDate(approvalDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.approval_date
     *
     * @param approvalDate the value for hq_goods.approval_date
     *
     * @mbg.generated
     */
    public void setApprovalDate(Integer approvalDate) {
        this.approvalDate = approvalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.validity_date
     *
     * @return the value of hq_goods.validity_date
     *
     * @mbg.generated
     */
    public String getValidityDate() {
        return validityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withValidityDate(String validityDate) {
        this.setValidityDate(validityDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.validity_date
     *
     * @param validityDate the value for hq_goods.validity_date
     *
     * @mbg.generated
     */
    public void setValidityDate(String validityDate) {
        this.validityDate = validityDate == null ? null : validityDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.license
     *
     * @return the value of hq_goods.license
     *
     * @mbg.generated
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withLicense(String license) {
        this.setLicense(license);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.license
     *
     * @param license the value for hq_goods.license
     *
     * @mbg.generated
     */
    public void setLicense(String license) {
        this.license = license == null ? null : license.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.remark3
     *
     * @return the value of hq_goods.remark3
     *
     * @mbg.generated
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withRemark3(String remark3) {
        this.setRemark3(remark3);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.remark3
     *
     * @param remark3 the value for hq_goods.remark3
     *
     * @mbg.generated
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.skills
     *
     * @return the value of hq_goods.skills
     *
     * @mbg.generated
     */
    public String getSkills() {
        return skills;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withSkills(String skills) {
        this.setSkills(skills);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.skills
     *
     * @param skills the value for hq_goods.skills
     *
     * @mbg.generated
     */
    public void setSkills(String skills) {
        this.skills = skills == null ? null : skills.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.keywords
     *
     * @return the value of hq_goods.keywords
     *
     * @mbg.generated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withKeywords(String keywords) {
        this.setKeywords(keywords);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.keywords
     *
     * @param keywords the value for hq_goods.keywords
     *
     * @mbg.generated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.like_num
     *
     * @return the value of hq_goods.like_num
     *
     * @mbg.generated
     */
    public Integer getLikeNum() {
        return likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withLikeNum(Integer likeNum) {
        this.setLikeNum(likeNum);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.like_num
     *
     * @param likeNum the value for hq_goods.like_num
     *
     * @mbg.generated
     */
    public void setLikeNum(Integer likeNum) {
        this.likeNum = likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.used_num
     *
     * @return the value of hq_goods.used_num
     *
     * @mbg.generated
     */
    public Integer getUsedNum() {
        return usedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withUsedNum(Integer usedNum) {
        this.setUsedNum(usedNum);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.used_num
     *
     * @param usedNum the value for hq_goods.used_num
     *
     * @mbg.generated
     */
    public void setUsedNum(Integer usedNum) {
        this.usedNum = usedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.fromz
     *
     * @return the value of hq_goods.fromz
     *
     * @mbg.generated
     */
    public String getFromz() {
        return fromz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withFromz(String fromz) {
        this.setFromz(fromz);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.fromz
     *
     * @param fromz the value for hq_goods.fromz
     *
     * @mbg.generated
     */
    public void setFromz(String fromz) {
        this.fromz = fromz == null ? null : fromz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.flag
     *
     * @return the value of hq_goods.flag
     *
     * @mbg.generated
     */
    public Boolean getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withFlag(Boolean flag) {
        this.setFlag(flag);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.flag
     *
     * @param flag the value for hq_goods.flag
     *
     * @mbg.generated
     */
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.record_num
     *
     * @return the value of hq_goods.record_num
     *
     * @mbg.generated
     */
    public String getRecordNum() {
        return recordNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withRecordNum(String recordNum) {
        this.setRecordNum(recordNum);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.record_num
     *
     * @param recordNum the value for hq_goods.record_num
     *
     * @mbg.generated
     */
    public void setRecordNum(String recordNum) {
        this.recordNum = recordNum == null ? null : recordNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.record_date
     *
     * @return the value of hq_goods.record_date
     *
     * @mbg.generated
     */
    public Integer getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withRecordDate(Integer recordDate) {
        this.setRecordDate(recordDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.record_date
     *
     * @param recordDate the value for hq_goods.record_date
     *
     * @mbg.generated
     */
    public void setRecordDate(Integer recordDate) {
        this.recordDate = recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.is_record
     *
     * @return the value of hq_goods.is_record
     *
     * @mbg.generated
     */
    public Boolean getIsRecord() {
        return isRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withIsRecord(Boolean isRecord) {
        this.setIsRecord(isRecord);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.is_record
     *
     * @param isRecord the value for hq_goods.is_record
     *
     * @mbg.generated
     */
    public void setIsRecord(Boolean isRecord) {
        this.isRecord = isRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.actual_company
     *
     * @return the value of hq_goods.actual_company
     *
     * @mbg.generated
     */
    public String getActualCompany() {
        return actualCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withActualCompany(String actualCompany) {
        this.setActualCompany(actualCompany);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.actual_company
     *
     * @param actualCompany the value for hq_goods.actual_company
     *
     * @mbg.generated
     */
    public void setActualCompany(String actualCompany) {
        this.actualCompany = actualCompany == null ? null : actualCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.actual_company_address
     *
     * @return the value of hq_goods.actual_company_address
     *
     * @mbg.generated
     */
    public String getActualCompanyAddress() {
        return actualCompanyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withActualCompanyAddress(String actualCompanyAddress) {
        this.setActualCompanyAddress(actualCompanyAddress);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.actual_company_address
     *
     * @param actualCompanyAddress the value for hq_goods.actual_company_address
     *
     * @mbg.generated
     */
    public void setActualCompanyAddress(String actualCompanyAddress) {
        this.actualCompanyAddress = actualCompanyAddress == null ? null : actualCompanyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.data_type
     *
     * @return the value of hq_goods.data_type
     *
     * @mbg.generated
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withDataType(Integer dataType) {
        this.setDataType(dataType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.data_type
     *
     * @param dataType the value for hq_goods.data_type
     *
     * @mbg.generated
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.china_company
     *
     * @return the value of hq_goods.china_company
     *
     * @mbg.generated
     */
    public String getChinaCompany() {
        return chinaCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withChinaCompany(String chinaCompany) {
        this.setChinaCompany(chinaCompany);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.china_company
     *
     * @param chinaCompany the value for hq_goods.china_company
     *
     * @mbg.generated
     */
    public void setChinaCompany(String chinaCompany) {
        this.chinaCompany = chinaCompany == null ? null : chinaCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.china_address
     *
     * @return the value of hq_goods.china_address
     *
     * @mbg.generated
     */
    public String getChinaAddress() {
        return chinaAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withChinaAddress(String chinaAddress) {
        this.setChinaAddress(chinaAddress);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.china_address
     *
     * @param chinaAddress the value for hq_goods.china_address
     *
     * @mbg.generated
     */
    public void setChinaAddress(String chinaAddress) {
        this.chinaAddress = chinaAddress == null ? null : chinaAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.country
     *
     * @return the value of hq_goods.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withCountry(String country) {
        this.setCountry(country);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.country
     *
     * @param country the value for hq_goods.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.instruction
     *
     * @return the value of hq_goods.instruction
     *
     * @mbg.generated
     */
    public String getInstruction() {
        return instruction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withInstruction(String instruction) {
        this.setInstruction(instruction);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.instruction
     *
     * @param instruction the value for hq_goods.instruction
     *
     * @mbg.generated
     */
    public void setInstruction(String instruction) {
        this.instruction = instruction == null ? null : instruction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.brand
     *
     * @return the value of hq_goods.brand
     *
     * @mbg.generated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withBrand(String brand) {
        this.setBrand(brand);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.brand
     *
     * @param brand the value for hq_goods.brand
     *
     * @mbg.generated
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.cname
     *
     * @return the value of hq_goods.cname
     *
     * @mbg.generated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withCname(String cname) {
        this.setCname(cname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.cname
     *
     * @param cname the value for hq_goods.cname
     *
     * @mbg.generated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.remark
     *
     * @return the value of hq_goods.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withRemark(String remark) {
        this.setRemark(remark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.remark
     *
     * @param remark the value for hq_goods.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.processid
     *
     * @return the value of hq_goods.processid
     *
     * @mbg.generated
     */
    public String getProcessid() {
        return processid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withProcessid(String processid) {
        this.setProcessid(processid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.processid
     *
     * @param processid the value for hq_goods.processid
     *
     * @mbg.generated
     */
    public void setProcessid(String processid) {
        this.processid = processid == null ? null : processid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.ishas
     *
     * @return the value of hq_goods.ishas
     *
     * @mbg.generated
     */
    public Boolean getIshas() {
        return ishas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withIshas(Boolean ishas) {
        this.setIshas(ishas);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.ishas
     *
     * @param ishas the value for hq_goods.ishas
     *
     * @mbg.generated
     */
    public void setIshas(Boolean ishas) {
        this.ishas = ishas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.iscag
     *
     * @return the value of hq_goods.iscag
     *
     * @mbg.generated
     */
    public Boolean getIscag() {
        return iscag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withIscag(Boolean iscag) {
        this.setIscag(iscag);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.iscag
     *
     * @param iscag the value for hq_goods.iscag
     *
     * @mbg.generated
     */
    public void setIscag(Boolean iscag) {
        this.iscag = iscag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.skillsUrl
     *
     * @return the value of hq_goods.skillsUrl
     *
     * @mbg.generated
     */
    public String getSkillsurl() {
        return skillsurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withSkillsurl(String skillsurl) {
        this.setSkillsurl(skillsurl);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.skillsUrl
     *
     * @param skillsurl the value for hq_goods.skillsUrl
     *
     * @mbg.generated
     */
    public void setSkillsurl(String skillsurl) {
        this.skillsurl = skillsurl == null ? null : skillsurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.categoryStr
     *
     * @return the value of hq_goods.categoryStr
     *
     * @mbg.generated
     */
    public String getCategorystr() {
        return categorystr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withCategorystr(String categorystr) {
        this.setCategorystr(categorystr);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.categoryStr
     *
     * @param categorystr the value for hq_goods.categoryStr
     *
     * @mbg.generated
     */
    public void setCategorystr(String categorystr) {
        this.categorystr = categorystr == null ? null : categorystr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.likecount
     *
     * @return the value of hq_goods.likecount
     *
     * @mbg.generated
     */
    public Integer getLikecount() {
        return likecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withLikecount(Integer likecount) {
        this.setLikecount(likecount);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.likecount
     *
     * @param likecount the value for hq_goods.likecount
     *
     * @mbg.generated
     */
    public void setLikecount(Integer likecount) {
        this.likecount = likecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.commentcount
     *
     * @return the value of hq_goods.commentcount
     *
     * @mbg.generated
     */
    public Integer getCommentcount() {
        return commentcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withCommentcount(Integer commentcount) {
        this.setCommentcount(commentcount);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.commentcount
     *
     * @param commentcount the value for hq_goods.commentcount
     *
     * @mbg.generated
     */
    public void setCommentcount(Integer commentcount) {
        this.commentcount = commentcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.notlikecount
     *
     * @return the value of hq_goods.notlikecount
     *
     * @mbg.generated
     */
    public Integer getNotlikecount() {
        return notlikecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withNotlikecount(Integer notlikecount) {
        this.setNotlikecount(notlikecount);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.notlikecount
     *
     * @param notlikecount the value for hq_goods.notlikecount
     *
     * @mbg.generated
     */
    public void setNotlikecount(Integer notlikecount) {
        this.notlikecount = notlikecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.mid
     *
     * @return the value of hq_goods.mid
     *
     * @mbg.generated
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withMid(String mid) {
        this.setMid(mid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.mid
     *
     * @param mid the value for hq_goods.mid
     *
     * @mbg.generated
     */
    public void setMid(String mid) {
        this.mid = mid == null ? null : mid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.ismodify
     *
     * @return the value of hq_goods.ismodify
     *
     * @mbg.generated
     */
    public Boolean getIsmodify() {
        return ismodify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withIsmodify(Boolean ismodify) {
        this.setIsmodify(ismodify);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.ismodify
     *
     * @param ismodify the value for hq_goods.ismodify
     *
     * @mbg.generated
     */
    public void setIsmodify(Boolean ismodify) {
        this.ismodify = ismodify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.new_goods_title
     *
     * @return the value of hq_goods.new_goods_title
     *
     * @mbg.generated
     */
    public String getNewGoodsTitle() {
        return newGoodsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withNewGoodsTitle(String newGoodsTitle) {
        this.setNewGoodsTitle(newGoodsTitle);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.new_goods_title
     *
     * @param newGoodsTitle the value for hq_goods.new_goods_title
     *
     * @mbg.generated
     */
    public void setNewGoodsTitle(String newGoodsTitle) {
        this.newGoodsTitle = newGoodsTitle == null ? null : newGoodsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.doyenid
     *
     * @return the value of hq_goods.doyenid
     *
     * @mbg.generated
     */
    public Integer getDoyenid() {
        return doyenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withDoyenid(Integer doyenid) {
        this.setDoyenid(doyenid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.doyenid
     *
     * @param doyenid the value for hq_goods.doyenid
     *
     * @mbg.generated
     */
    public void setDoyenid(Integer doyenid) {
        this.doyenid = doyenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.isdoyenmodify
     *
     * @return the value of hq_goods.isdoyenmodify
     *
     * @mbg.generated
     */
    public Integer getIsdoyenmodify() {
        return isdoyenmodify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withIsdoyenmodify(Integer isdoyenmodify) {
        this.setIsdoyenmodify(isdoyenmodify);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.isdoyenmodify
     *
     * @param isdoyenmodify the value for hq_goods.isdoyenmodify
     *
     * @mbg.generated
     */
    public void setIsdoyenmodify(Integer isdoyenmodify) {
        this.isdoyenmodify = isdoyenmodify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.price
     *
     * @return the value of hq_goods.price
     *
     * @mbg.generated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withPrice(String price) {
        this.setPrice(price);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.price
     *
     * @param price the value for hq_goods.price
     *
     * @mbg.generated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.capacity
     *
     * @return the value of hq_goods.capacity
     *
     * @mbg.generated
     */
    public String getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withCapacity(String capacity) {
        this.setCapacity(capacity);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.capacity
     *
     * @param capacity the value for hq_goods.capacity
     *
     * @mbg.generated
     */
    public void setCapacity(String capacity) {
        this.capacity = capacity == null ? null : capacity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.sell_price
     *
     * @return the value of hq_goods.sell_price
     *
     * @mbg.generated
     */
    public BigDecimal getSellPrice() {
        return sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withSellPrice(BigDecimal sellPrice) {
        this.setSellPrice(sellPrice);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.sell_price
     *
     * @param sellPrice the value for hq_goods.sell_price
     *
     * @mbg.generated
     */
    public void setSellPrice(BigDecimal sellPrice) {
        this.sellPrice = sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.sell_capacity
     *
     * @return the value of hq_goods.sell_capacity
     *
     * @mbg.generated
     */
    public String getSellCapacity() {
        return sellCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withSellCapacity(String sellCapacity) {
        this.setSellCapacity(sellCapacity);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.sell_capacity
     *
     * @param sellCapacity the value for hq_goods.sell_capacity
     *
     * @mbg.generated
     */
    public void setSellCapacity(String sellCapacity) {
        this.sellCapacity = sellCapacity == null ? null : sellCapacity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.hidden_skin
     *
     * @return the value of hq_goods.hidden_skin
     *
     * @mbg.generated
     */
    public Integer getHiddenSkin() {
        return hiddenSkin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withHiddenSkin(Integer hiddenSkin) {
        this.setHiddenSkin(hiddenSkin);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.hidden_skin
     *
     * @param hiddenSkin the value for hq_goods.hidden_skin
     *
     * @mbg.generated
     */
    public void setHiddenSkin(Integer hiddenSkin) {
        this.hiddenSkin = hiddenSkin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.cps_type
     *
     * @return the value of hq_goods.cps_type
     *
     * @mbg.generated
     */
    public String getCpsType() {
        return cpsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withCpsType(String cpsType) {
        this.setCpsType(cpsType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.cps_type
     *
     * @param cpsType the value for hq_goods.cps_type
     *
     * @mbg.generated
     */
    public void setCpsType(String cpsType) {
        this.cpsType = cpsType == null ? null : cpsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods.price_unit
     *
     * @return the value of hq_goods.price_unit
     *
     * @mbg.generated
     */
    public Integer getPriceUnit() {
        return priceUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods
     *
     * @mbg.generated
     */
    public Goods withPriceUnit(Integer priceUnit) {
        this.setPriceUnit(priceUnit);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods.price_unit
     *
     * @param priceUnit the value for hq_goods.price_unit
     *
     * @mbg.generated
     */
    public void setPriceUnit(Integer priceUnit) {
        this.priceUnit = priceUnit;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table hq_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        brandId("brand_id"),
        tstamp("tstamp"),
        crdate("crdate"),
        startdate("startdate"),
        overdate("overdate"),
        cruserId("cruser_id"),
        deleted("deleted"),
        hidden("hidden"),
        mergeId("merge_id"),
        sorting("sorting"),
        hit("hit"),
        hot("hot"),
        top("top"),
        title("title"),
        alias("alias"),
        alias2("alias_2"),
        image("image"),
        category("category"),
        company("company"),
        companyEnglish("company_english"),
        address("address"),
        approval("approval"),
        state("state"),
        approvalDate("approval_date"),
        validityDate("validity_date"),
        license("license"),
        remark3("remark3"),
        skills("skills"),
        keywords("keywords"),
        likeNum("like_num"),
        usedNum("used_num"),
        fromz("fromz"),
        flag("flag"),
        recordNum("record_num"),
        recordDate("record_date"),
        isRecord("is_record"),
        actualCompany("actual_company"),
        actualCompanyAddress("actual_company_address"),
        dataType("data_type"),
        chinaCompany("china_company"),
        chinaAddress("china_address"),
        country("country"),
        instruction("instruction"),
        brand("brand"),
        cname("cname"),
        remark("remark"),
        processid("processid"),
        ishas("ishas"),
        iscag("iscag"),
        skillsurl("skillsUrl"),
        categorystr("categoryStr"),
        likecount("likecount"),
        commentcount("commentcount"),
        notlikecount("notlikecount"),
        mid("mid"),
        ismodify("ismodify"),
        newGoodsTitle("new_goods_title"),
        doyenid("doyenid"),
        isdoyenmodify("isdoyenmodify"),
        price("price"),
        capacity("capacity"),
        sellPrice("sell_price"),
        sellCapacity("sell_capacity"),
        hiddenSkin("hidden_skin"),
        cpsType("cps_type"),
        priceUnit("price_unit"),
        content("content"),
        explainz("explainz"),
        gcsort("gcsort"),
        tips("tips"),
        doyencomment("doyencomment"),
        cps("cps");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hq_goods
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}