package cn.bevol.internal.dao;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hq_goods_tag_result
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class GoodsTagResult implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_result.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *    产品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_result.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     * Database Column Remarks:
     *   自动筛选的结果
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_result.auto_tag_ids
     *
     * @mbg.generated
     */
    private String autoTagIds;

    /**
     * Database Column Remarks:
     *   自动计算的名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_result.auto_tag_names
     *
     * @mbg.generated
     */
    private String autoTagNames;

    /**
     * Database Column Remarks:
     *   手动筛选的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_result.made_tag_ids
     *
     * @mbg.generated
     */
    private String madeTagIds;

    /**
     * Database Column Remarks:
     *   手动筛选的名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_result.made_tag_names
     *
     * @mbg.generated
     */
    private String madeTagNames;

    /**
     * Database Column Remarks:
     *   正式使用的
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_result.tag_ids
     *
     * @mbg.generated
     */
    private String tagIds;

    /**
     * Database Column Remarks:
     *   正式使用的名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_result.tag_names
     *
     * @mbg.generated
     */
    private String tagNames;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_result.create_stamp
     *
     * @mbg.generated
     */
    private Integer createStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_result.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * Database Column Remarks:
     *   1表示隐藏
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_result.hidden
     *
     * @mbg.generated
     */
    private Boolean hidden;

    /**
     * Database Column Remarks:
     *   最近一次的更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_result.update_time
     *
     * @mbg.generated
     */
    private Integer updateTime;

    /**
     * Database Column Remarks:
     *   是否手动删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_goods_tag_result.made_delete
     *
     * @mbg.generated
     */
    private Boolean madeDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_result.id
     *
     * @return the value of hq_goods_tag_result.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public GoodsTagResult withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_result.id
     *
     * @param id the value for hq_goods_tag_result.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_result.goods_id
     *
     * @return the value of hq_goods_tag_result.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public GoodsTagResult withGoodsId(Integer goodsId) {
        this.setGoodsId(goodsId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_result.goods_id
     *
     * @param goodsId the value for hq_goods_tag_result.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_result.auto_tag_ids
     *
     * @return the value of hq_goods_tag_result.auto_tag_ids
     *
     * @mbg.generated
     */
    public String getAutoTagIds() {
        return autoTagIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public GoodsTagResult withAutoTagIds(String autoTagIds) {
        this.setAutoTagIds(autoTagIds);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_result.auto_tag_ids
     *
     * @param autoTagIds the value for hq_goods_tag_result.auto_tag_ids
     *
     * @mbg.generated
     */
    public void setAutoTagIds(String autoTagIds) {
        this.autoTagIds = autoTagIds == null ? null : autoTagIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_result.auto_tag_names
     *
     * @return the value of hq_goods_tag_result.auto_tag_names
     *
     * @mbg.generated
     */
    public String getAutoTagNames() {
        return autoTagNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public GoodsTagResult withAutoTagNames(String autoTagNames) {
        this.setAutoTagNames(autoTagNames);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_result.auto_tag_names
     *
     * @param autoTagNames the value for hq_goods_tag_result.auto_tag_names
     *
     * @mbg.generated
     */
    public void setAutoTagNames(String autoTagNames) {
        this.autoTagNames = autoTagNames == null ? null : autoTagNames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_result.made_tag_ids
     *
     * @return the value of hq_goods_tag_result.made_tag_ids
     *
     * @mbg.generated
     */
    public String getMadeTagIds() {
        return madeTagIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public GoodsTagResult withMadeTagIds(String madeTagIds) {
        this.setMadeTagIds(madeTagIds);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_result.made_tag_ids
     *
     * @param madeTagIds the value for hq_goods_tag_result.made_tag_ids
     *
     * @mbg.generated
     */
    public void setMadeTagIds(String madeTagIds) {
        this.madeTagIds = madeTagIds == null ? null : madeTagIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_result.made_tag_names
     *
     * @return the value of hq_goods_tag_result.made_tag_names
     *
     * @mbg.generated
     */
    public String getMadeTagNames() {
        return madeTagNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public GoodsTagResult withMadeTagNames(String madeTagNames) {
        this.setMadeTagNames(madeTagNames);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_result.made_tag_names
     *
     * @param madeTagNames the value for hq_goods_tag_result.made_tag_names
     *
     * @mbg.generated
     */
    public void setMadeTagNames(String madeTagNames) {
        this.madeTagNames = madeTagNames == null ? null : madeTagNames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_result.tag_ids
     *
     * @return the value of hq_goods_tag_result.tag_ids
     *
     * @mbg.generated
     */
    public String getTagIds() {
        return tagIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public GoodsTagResult withTagIds(String tagIds) {
        this.setTagIds(tagIds);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_result.tag_ids
     *
     * @param tagIds the value for hq_goods_tag_result.tag_ids
     *
     * @mbg.generated
     */
    public void setTagIds(String tagIds) {
        this.tagIds = tagIds == null ? null : tagIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_result.tag_names
     *
     * @return the value of hq_goods_tag_result.tag_names
     *
     * @mbg.generated
     */
    public String getTagNames() {
        return tagNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public GoodsTagResult withTagNames(String tagNames) {
        this.setTagNames(tagNames);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_result.tag_names
     *
     * @param tagNames the value for hq_goods_tag_result.tag_names
     *
     * @mbg.generated
     */
    public void setTagNames(String tagNames) {
        this.tagNames = tagNames == null ? null : tagNames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_result.create_stamp
     *
     * @return the value of hq_goods_tag_result.create_stamp
     *
     * @mbg.generated
     */
    public Integer getCreateStamp() {
        return createStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public GoodsTagResult withCreateStamp(Integer createStamp) {
        this.setCreateStamp(createStamp);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_result.create_stamp
     *
     * @param createStamp the value for hq_goods_tag_result.create_stamp
     *
     * @mbg.generated
     */
    public void setCreateStamp(Integer createStamp) {
        this.createStamp = createStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_result.status
     *
     * @return the value of hq_goods_tag_result.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public GoodsTagResult withStatus(Boolean status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_result.status
     *
     * @param status the value for hq_goods_tag_result.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_result.hidden
     *
     * @return the value of hq_goods_tag_result.hidden
     *
     * @mbg.generated
     */
    public Boolean getHidden() {
        return hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public GoodsTagResult withHidden(Boolean hidden) {
        this.setHidden(hidden);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_result.hidden
     *
     * @param hidden the value for hq_goods_tag_result.hidden
     *
     * @mbg.generated
     */
    public void setHidden(Boolean hidden) {
        this.hidden = hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_result.update_time
     *
     * @return the value of hq_goods_tag_result.update_time
     *
     * @mbg.generated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public GoodsTagResult withUpdateTime(Integer updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_result.update_time
     *
     * @param updateTime the value for hq_goods_tag_result.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_goods_tag_result.made_delete
     *
     * @return the value of hq_goods_tag_result.made_delete
     *
     * @mbg.generated
     */
    public Boolean getMadeDelete() {
        return madeDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public GoodsTagResult withMadeDelete(Boolean madeDelete) {
        this.setMadeDelete(madeDelete);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_goods_tag_result.made_delete
     *
     * @param madeDelete the value for hq_goods_tag_result.made_delete
     *
     * @mbg.generated
     */
    public void setMadeDelete(Boolean madeDelete) {
        this.madeDelete = madeDelete;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        goodsId("goods_id"),
        autoTagIds("auto_tag_ids"),
        autoTagNames("auto_tag_names"),
        madeTagIds("made_tag_ids"),
        madeTagNames("made_tag_names"),
        tagIds("tag_ids"),
        tagNames("tag_names"),
        createStamp("create_stamp"),
        status("status"),
        hidden("hidden"),
        updateTime("update_time"),
        madeDelete("made_delete");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hq_goods_tag_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_tag_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_tag_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_tag_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_tag_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_tag_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}