package cn.bevol.internal.dao;

import java.util.ArrayList;
import java.util.List;

public class GoodsTagResultExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public GoodsTagResultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public GoodsTagResultExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public GoodsTagResultExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNull() {
            addCriterion("goods_id is null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNotNull() {
            addCriterion("goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdEqualTo(Integer value) {
            addCriterion("goods_id =", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotEqualTo(Integer value) {
            addCriterion("goods_id <>", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThan(Integer value) {
            addCriterion("goods_id >", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("goods_id >=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThan(Integer value) {
            addCriterion("goods_id <", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThanOrEqualTo(Integer value) {
            addCriterion("goods_id <=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIn(List<Integer> values) {
            addCriterion("goods_id in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotIn(List<Integer> values) {
            addCriterion("goods_id not in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdBetween(Integer value1, Integer value2) {
            addCriterion("goods_id between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("goods_id not between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andAutoTagIdsIsNull() {
            addCriterion("auto_tag_ids is null");
            return (Criteria) this;
        }

        public Criteria andAutoTagIdsIsNotNull() {
            addCriterion("auto_tag_ids is not null");
            return (Criteria) this;
        }

        public Criteria andAutoTagIdsEqualTo(String value) {
            addCriterion("auto_tag_ids =", value, "autoTagIds");
            return (Criteria) this;
        }

        public Criteria andAutoTagIdsNotEqualTo(String value) {
            addCriterion("auto_tag_ids <>", value, "autoTagIds");
            return (Criteria) this;
        }

        public Criteria andAutoTagIdsGreaterThan(String value) {
            addCriterion("auto_tag_ids >", value, "autoTagIds");
            return (Criteria) this;
        }

        public Criteria andAutoTagIdsGreaterThanOrEqualTo(String value) {
            addCriterion("auto_tag_ids >=", value, "autoTagIds");
            return (Criteria) this;
        }

        public Criteria andAutoTagIdsLessThan(String value) {
            addCriterion("auto_tag_ids <", value, "autoTagIds");
            return (Criteria) this;
        }

        public Criteria andAutoTagIdsLessThanOrEqualTo(String value) {
            addCriterion("auto_tag_ids <=", value, "autoTagIds");
            return (Criteria) this;
        }

        public Criteria andAutoTagIdsLike(String value) {
            addCriterion("auto_tag_ids like", value, "autoTagIds");
            return (Criteria) this;
        }

        public Criteria andAutoTagIdsNotLike(String value) {
            addCriterion("auto_tag_ids not like", value, "autoTagIds");
            return (Criteria) this;
        }

        public Criteria andAutoTagIdsIn(List<String> values) {
            addCriterion("auto_tag_ids in", values, "autoTagIds");
            return (Criteria) this;
        }

        public Criteria andAutoTagIdsNotIn(List<String> values) {
            addCriterion("auto_tag_ids not in", values, "autoTagIds");
            return (Criteria) this;
        }

        public Criteria andAutoTagIdsBetween(String value1, String value2) {
            addCriterion("auto_tag_ids between", value1, value2, "autoTagIds");
            return (Criteria) this;
        }

        public Criteria andAutoTagIdsNotBetween(String value1, String value2) {
            addCriterion("auto_tag_ids not between", value1, value2, "autoTagIds");
            return (Criteria) this;
        }

        public Criteria andAutoTagNamesIsNull() {
            addCriterion("auto_tag_names is null");
            return (Criteria) this;
        }

        public Criteria andAutoTagNamesIsNotNull() {
            addCriterion("auto_tag_names is not null");
            return (Criteria) this;
        }

        public Criteria andAutoTagNamesEqualTo(String value) {
            addCriterion("auto_tag_names =", value, "autoTagNames");
            return (Criteria) this;
        }

        public Criteria andAutoTagNamesNotEqualTo(String value) {
            addCriterion("auto_tag_names <>", value, "autoTagNames");
            return (Criteria) this;
        }

        public Criteria andAutoTagNamesGreaterThan(String value) {
            addCriterion("auto_tag_names >", value, "autoTagNames");
            return (Criteria) this;
        }

        public Criteria andAutoTagNamesGreaterThanOrEqualTo(String value) {
            addCriterion("auto_tag_names >=", value, "autoTagNames");
            return (Criteria) this;
        }

        public Criteria andAutoTagNamesLessThan(String value) {
            addCriterion("auto_tag_names <", value, "autoTagNames");
            return (Criteria) this;
        }

        public Criteria andAutoTagNamesLessThanOrEqualTo(String value) {
            addCriterion("auto_tag_names <=", value, "autoTagNames");
            return (Criteria) this;
        }

        public Criteria andAutoTagNamesLike(String value) {
            addCriterion("auto_tag_names like", value, "autoTagNames");
            return (Criteria) this;
        }

        public Criteria andAutoTagNamesNotLike(String value) {
            addCriterion("auto_tag_names not like", value, "autoTagNames");
            return (Criteria) this;
        }

        public Criteria andAutoTagNamesIn(List<String> values) {
            addCriterion("auto_tag_names in", values, "autoTagNames");
            return (Criteria) this;
        }

        public Criteria andAutoTagNamesNotIn(List<String> values) {
            addCriterion("auto_tag_names not in", values, "autoTagNames");
            return (Criteria) this;
        }

        public Criteria andAutoTagNamesBetween(String value1, String value2) {
            addCriterion("auto_tag_names between", value1, value2, "autoTagNames");
            return (Criteria) this;
        }

        public Criteria andAutoTagNamesNotBetween(String value1, String value2) {
            addCriterion("auto_tag_names not between", value1, value2, "autoTagNames");
            return (Criteria) this;
        }

        public Criteria andMadeTagIdsIsNull() {
            addCriterion("made_tag_ids is null");
            return (Criteria) this;
        }

        public Criteria andMadeTagIdsIsNotNull() {
            addCriterion("made_tag_ids is not null");
            return (Criteria) this;
        }

        public Criteria andMadeTagIdsEqualTo(String value) {
            addCriterion("made_tag_ids =", value, "madeTagIds");
            return (Criteria) this;
        }

        public Criteria andMadeTagIdsNotEqualTo(String value) {
            addCriterion("made_tag_ids <>", value, "madeTagIds");
            return (Criteria) this;
        }

        public Criteria andMadeTagIdsGreaterThan(String value) {
            addCriterion("made_tag_ids >", value, "madeTagIds");
            return (Criteria) this;
        }

        public Criteria andMadeTagIdsGreaterThanOrEqualTo(String value) {
            addCriterion("made_tag_ids >=", value, "madeTagIds");
            return (Criteria) this;
        }

        public Criteria andMadeTagIdsLessThan(String value) {
            addCriterion("made_tag_ids <", value, "madeTagIds");
            return (Criteria) this;
        }

        public Criteria andMadeTagIdsLessThanOrEqualTo(String value) {
            addCriterion("made_tag_ids <=", value, "madeTagIds");
            return (Criteria) this;
        }

        public Criteria andMadeTagIdsLike(String value) {
            addCriterion("made_tag_ids like", value, "madeTagIds");
            return (Criteria) this;
        }

        public Criteria andMadeTagIdsNotLike(String value) {
            addCriterion("made_tag_ids not like", value, "madeTagIds");
            return (Criteria) this;
        }

        public Criteria andMadeTagIdsIn(List<String> values) {
            addCriterion("made_tag_ids in", values, "madeTagIds");
            return (Criteria) this;
        }

        public Criteria andMadeTagIdsNotIn(List<String> values) {
            addCriterion("made_tag_ids not in", values, "madeTagIds");
            return (Criteria) this;
        }

        public Criteria andMadeTagIdsBetween(String value1, String value2) {
            addCriterion("made_tag_ids between", value1, value2, "madeTagIds");
            return (Criteria) this;
        }

        public Criteria andMadeTagIdsNotBetween(String value1, String value2) {
            addCriterion("made_tag_ids not between", value1, value2, "madeTagIds");
            return (Criteria) this;
        }

        public Criteria andMadeTagNamesIsNull() {
            addCriterion("made_tag_names is null");
            return (Criteria) this;
        }

        public Criteria andMadeTagNamesIsNotNull() {
            addCriterion("made_tag_names is not null");
            return (Criteria) this;
        }

        public Criteria andMadeTagNamesEqualTo(String value) {
            addCriterion("made_tag_names =", value, "madeTagNames");
            return (Criteria) this;
        }

        public Criteria andMadeTagNamesNotEqualTo(String value) {
            addCriterion("made_tag_names <>", value, "madeTagNames");
            return (Criteria) this;
        }

        public Criteria andMadeTagNamesGreaterThan(String value) {
            addCriterion("made_tag_names >", value, "madeTagNames");
            return (Criteria) this;
        }

        public Criteria andMadeTagNamesGreaterThanOrEqualTo(String value) {
            addCriterion("made_tag_names >=", value, "madeTagNames");
            return (Criteria) this;
        }

        public Criteria andMadeTagNamesLessThan(String value) {
            addCriterion("made_tag_names <", value, "madeTagNames");
            return (Criteria) this;
        }

        public Criteria andMadeTagNamesLessThanOrEqualTo(String value) {
            addCriterion("made_tag_names <=", value, "madeTagNames");
            return (Criteria) this;
        }

        public Criteria andMadeTagNamesLike(String value) {
            addCriterion("made_tag_names like", value, "madeTagNames");
            return (Criteria) this;
        }

        public Criteria andMadeTagNamesNotLike(String value) {
            addCriterion("made_tag_names not like", value, "madeTagNames");
            return (Criteria) this;
        }

        public Criteria andMadeTagNamesIn(List<String> values) {
            addCriterion("made_tag_names in", values, "madeTagNames");
            return (Criteria) this;
        }

        public Criteria andMadeTagNamesNotIn(List<String> values) {
            addCriterion("made_tag_names not in", values, "madeTagNames");
            return (Criteria) this;
        }

        public Criteria andMadeTagNamesBetween(String value1, String value2) {
            addCriterion("made_tag_names between", value1, value2, "madeTagNames");
            return (Criteria) this;
        }

        public Criteria andMadeTagNamesNotBetween(String value1, String value2) {
            addCriterion("made_tag_names not between", value1, value2, "madeTagNames");
            return (Criteria) this;
        }

        public Criteria andTagIdsIsNull() {
            addCriterion("tag_ids is null");
            return (Criteria) this;
        }

        public Criteria andTagIdsIsNotNull() {
            addCriterion("tag_ids is not null");
            return (Criteria) this;
        }

        public Criteria andTagIdsEqualTo(String value) {
            addCriterion("tag_ids =", value, "tagIds");
            return (Criteria) this;
        }

        public Criteria andTagIdsNotEqualTo(String value) {
            addCriterion("tag_ids <>", value, "tagIds");
            return (Criteria) this;
        }

        public Criteria andTagIdsGreaterThan(String value) {
            addCriterion("tag_ids >", value, "tagIds");
            return (Criteria) this;
        }

        public Criteria andTagIdsGreaterThanOrEqualTo(String value) {
            addCriterion("tag_ids >=", value, "tagIds");
            return (Criteria) this;
        }

        public Criteria andTagIdsLessThan(String value) {
            addCriterion("tag_ids <", value, "tagIds");
            return (Criteria) this;
        }

        public Criteria andTagIdsLessThanOrEqualTo(String value) {
            addCriterion("tag_ids <=", value, "tagIds");
            return (Criteria) this;
        }

        public Criteria andTagIdsLike(String value) {
            addCriterion("tag_ids like", value, "tagIds");
            return (Criteria) this;
        }

        public Criteria andTagIdsNotLike(String value) {
            addCriterion("tag_ids not like", value, "tagIds");
            return (Criteria) this;
        }

        public Criteria andTagIdsIn(List<String> values) {
            addCriterion("tag_ids in", values, "tagIds");
            return (Criteria) this;
        }

        public Criteria andTagIdsNotIn(List<String> values) {
            addCriterion("tag_ids not in", values, "tagIds");
            return (Criteria) this;
        }

        public Criteria andTagIdsBetween(String value1, String value2) {
            addCriterion("tag_ids between", value1, value2, "tagIds");
            return (Criteria) this;
        }

        public Criteria andTagIdsNotBetween(String value1, String value2) {
            addCriterion("tag_ids not between", value1, value2, "tagIds");
            return (Criteria) this;
        }

        public Criteria andTagNamesIsNull() {
            addCriterion("tag_names is null");
            return (Criteria) this;
        }

        public Criteria andTagNamesIsNotNull() {
            addCriterion("tag_names is not null");
            return (Criteria) this;
        }

        public Criteria andTagNamesEqualTo(String value) {
            addCriterion("tag_names =", value, "tagNames");
            return (Criteria) this;
        }

        public Criteria andTagNamesNotEqualTo(String value) {
            addCriterion("tag_names <>", value, "tagNames");
            return (Criteria) this;
        }

        public Criteria andTagNamesGreaterThan(String value) {
            addCriterion("tag_names >", value, "tagNames");
            return (Criteria) this;
        }

        public Criteria andTagNamesGreaterThanOrEqualTo(String value) {
            addCriterion("tag_names >=", value, "tagNames");
            return (Criteria) this;
        }

        public Criteria andTagNamesLessThan(String value) {
            addCriterion("tag_names <", value, "tagNames");
            return (Criteria) this;
        }

        public Criteria andTagNamesLessThanOrEqualTo(String value) {
            addCriterion("tag_names <=", value, "tagNames");
            return (Criteria) this;
        }

        public Criteria andTagNamesLike(String value) {
            addCriterion("tag_names like", value, "tagNames");
            return (Criteria) this;
        }

        public Criteria andTagNamesNotLike(String value) {
            addCriterion("tag_names not like", value, "tagNames");
            return (Criteria) this;
        }

        public Criteria andTagNamesIn(List<String> values) {
            addCriterion("tag_names in", values, "tagNames");
            return (Criteria) this;
        }

        public Criteria andTagNamesNotIn(List<String> values) {
            addCriterion("tag_names not in", values, "tagNames");
            return (Criteria) this;
        }

        public Criteria andTagNamesBetween(String value1, String value2) {
            addCriterion("tag_names between", value1, value2, "tagNames");
            return (Criteria) this;
        }

        public Criteria andTagNamesNotBetween(String value1, String value2) {
            addCriterion("tag_names not between", value1, value2, "tagNames");
            return (Criteria) this;
        }

        public Criteria andCreateStampIsNull() {
            addCriterion("create_stamp is null");
            return (Criteria) this;
        }

        public Criteria andCreateStampIsNotNull() {
            addCriterion("create_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andCreateStampEqualTo(Integer value) {
            addCriterion("create_stamp =", value, "createStamp");
            return (Criteria) this;
        }

        public Criteria andCreateStampNotEqualTo(Integer value) {
            addCriterion("create_stamp <>", value, "createStamp");
            return (Criteria) this;
        }

        public Criteria andCreateStampGreaterThan(Integer value) {
            addCriterion("create_stamp >", value, "createStamp");
            return (Criteria) this;
        }

        public Criteria andCreateStampGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_stamp >=", value, "createStamp");
            return (Criteria) this;
        }

        public Criteria andCreateStampLessThan(Integer value) {
            addCriterion("create_stamp <", value, "createStamp");
            return (Criteria) this;
        }

        public Criteria andCreateStampLessThanOrEqualTo(Integer value) {
            addCriterion("create_stamp <=", value, "createStamp");
            return (Criteria) this;
        }

        public Criteria andCreateStampIn(List<Integer> values) {
            addCriterion("create_stamp in", values, "createStamp");
            return (Criteria) this;
        }

        public Criteria andCreateStampNotIn(List<Integer> values) {
            addCriterion("create_stamp not in", values, "createStamp");
            return (Criteria) this;
        }

        public Criteria andCreateStampBetween(Integer value1, Integer value2) {
            addCriterion("create_stamp between", value1, value2, "createStamp");
            return (Criteria) this;
        }

        public Criteria andCreateStampNotBetween(Integer value1, Integer value2) {
            addCriterion("create_stamp not between", value1, value2, "createStamp");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Boolean value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Boolean value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Boolean value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Boolean value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Boolean> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Boolean> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andHiddenIsNull() {
            addCriterion("hidden is null");
            return (Criteria) this;
        }

        public Criteria andHiddenIsNotNull() {
            addCriterion("hidden is not null");
            return (Criteria) this;
        }

        public Criteria andHiddenEqualTo(Boolean value) {
            addCriterion("hidden =", value, "hidden");
            return (Criteria) this;
        }

        public Criteria andHiddenNotEqualTo(Boolean value) {
            addCriterion("hidden <>", value, "hidden");
            return (Criteria) this;
        }

        public Criteria andHiddenGreaterThan(Boolean value) {
            addCriterion("hidden >", value, "hidden");
            return (Criteria) this;
        }

        public Criteria andHiddenGreaterThanOrEqualTo(Boolean value) {
            addCriterion("hidden >=", value, "hidden");
            return (Criteria) this;
        }

        public Criteria andHiddenLessThan(Boolean value) {
            addCriterion("hidden <", value, "hidden");
            return (Criteria) this;
        }

        public Criteria andHiddenLessThanOrEqualTo(Boolean value) {
            addCriterion("hidden <=", value, "hidden");
            return (Criteria) this;
        }

        public Criteria andHiddenIn(List<Boolean> values) {
            addCriterion("hidden in", values, "hidden");
            return (Criteria) this;
        }

        public Criteria andHiddenNotIn(List<Boolean> values) {
            addCriterion("hidden not in", values, "hidden");
            return (Criteria) this;
        }

        public Criteria andHiddenBetween(Boolean value1, Boolean value2) {
            addCriterion("hidden between", value1, value2, "hidden");
            return (Criteria) this;
        }

        public Criteria andHiddenNotBetween(Boolean value1, Boolean value2) {
            addCriterion("hidden not between", value1, value2, "hidden");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Integer value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Integer value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Integer value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Integer value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Integer> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Integer> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Integer value1, Integer value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andMadeDeleteIsNull() {
            addCriterion("made_delete is null");
            return (Criteria) this;
        }

        public Criteria andMadeDeleteIsNotNull() {
            addCriterion("made_delete is not null");
            return (Criteria) this;
        }

        public Criteria andMadeDeleteEqualTo(Boolean value) {
            addCriterion("made_delete =", value, "madeDelete");
            return (Criteria) this;
        }

        public Criteria andMadeDeleteNotEqualTo(Boolean value) {
            addCriterion("made_delete <>", value, "madeDelete");
            return (Criteria) this;
        }

        public Criteria andMadeDeleteGreaterThan(Boolean value) {
            addCriterion("made_delete >", value, "madeDelete");
            return (Criteria) this;
        }

        public Criteria andMadeDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("made_delete >=", value, "madeDelete");
            return (Criteria) this;
        }

        public Criteria andMadeDeleteLessThan(Boolean value) {
            addCriterion("made_delete <", value, "madeDelete");
            return (Criteria) this;
        }

        public Criteria andMadeDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("made_delete <=", value, "madeDelete");
            return (Criteria) this;
        }

        public Criteria andMadeDeleteIn(List<Boolean> values) {
            addCriterion("made_delete in", values, "madeDelete");
            return (Criteria) this;
        }

        public Criteria andMadeDeleteNotIn(List<Boolean> values) {
            addCriterion("made_delete not in", values, "madeDelete");
            return (Criteria) this;
        }

        public Criteria andMadeDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("made_delete between", value1, value2, "madeDelete");
            return (Criteria) this;
        }

        public Criteria andMadeDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("made_delete not between", value1, value2, "madeDelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hq_goods_tag_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private GoodsTagResultExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_tag_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(GoodsTagResultExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_tag_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public GoodsTagResultExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hq_goods_tag_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table hq_goods_tag_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table hq_goods_tag_result
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hq_goods_tag_result
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}