package cn.bevol.internal.dao.mapper;

import cn.bevol.internal.dao.GoodsTagComposition;
import cn.bevol.internal.dao.GoodsTagCompositionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GoodsTagCompositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     */
    long countByExample(GoodsTagCompositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     */
    int insert(GoodsTagComposition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     */
    int insertSelective(GoodsTagComposition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     */
    List<GoodsTagComposition> selectByExampleWithRowbounds(GoodsTagCompositionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     */
    List<GoodsTagComposition> selectByExample(GoodsTagCompositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     */
    GoodsTagComposition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GoodsTagComposition record, @Param("example") GoodsTagCompositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GoodsTagComposition record, @Param("example") GoodsTagCompositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodsTagComposition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsTagComposition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<GoodsTagComposition> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<GoodsTagComposition> list, @Param("selective") GoodsTagComposition.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_composition
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GoodsTagComposition selectOneByExample(GoodsTagCompositionExample example);
}