package cn.bevol.internal.dao.mapper;

import cn.bevol.internal.dao.GoodsExt;
import cn.bevol.internal.dao.GoodsExtExample;
import cn.bevol.internal.dao.GoodsExtWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GoodsExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     */
    long countByExample(GoodsExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     */
    int insert(GoodsExtWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     */
    int insertSelective(GoodsExtWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     */
    List<GoodsExtWithBLOBs> selectByExampleWithBLOBsWithRowbounds(GoodsExtExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     */
    List<GoodsExtWithBLOBs> selectByExampleWithBLOBs(GoodsExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     */
    List<GoodsExt> selectByExampleWithRowbounds(GoodsExtExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     */
    List<GoodsExt> selectByExample(GoodsExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     */
    GoodsExtWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GoodsExtWithBLOBs record, @Param("example") GoodsExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") GoodsExtWithBLOBs record, @Param("example") GoodsExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GoodsExt record, @Param("example") GoodsExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodsExtWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(GoodsExtWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<GoodsExtWithBLOBs> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<GoodsExtWithBLOBs> list, @Param("selective") GoodsExtWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GoodsExt selectOneByExample(GoodsExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_ext
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GoodsExtWithBLOBs selectOneByExampleWithBLOBs(GoodsExtExample example);
}