package cn.bevol.statics.dao.mapper;

import cn.bevol.statics.dao.GoodsPolyCategory;
import cn.bevol.statics.dao.GoodsPolyCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GoodsPolyCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_poly_category
     *
     * @mbg.generated
     */
    long countByExample(GoodsPolyCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_poly_category
     *
     * @mbg.generated
     */
    int insert(GoodsPolyCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_poly_category
     *
     * @mbg.generated
     */
    int insertSelective(GoodsPolyCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_poly_category
     *
     * @mbg.generated
     */
    List<GoodsPolyCategory> selectByExampleWithBLOBsWithRowbounds(GoodsPolyCategoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_poly_category
     *
     * @mbg.generated
     */
    List<GoodsPolyCategory> selectByExampleWithBLOBs(GoodsPolyCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_poly_category
     *
     * @mbg.generated
     */
    List<GoodsPolyCategory> selectByExampleWithRowbounds(GoodsPolyCategoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_poly_category
     *
     * @mbg.generated
     */
    List<GoodsPolyCategory> selectByExample(GoodsPolyCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_poly_category
     *
     * @mbg.generated
     */
    GoodsPolyCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_poly_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GoodsPolyCategory record, @Param("example") GoodsPolyCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_poly_category
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") GoodsPolyCategory record, @Param("example") GoodsPolyCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_poly_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GoodsPolyCategory record, @Param("example") GoodsPolyCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_poly_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodsPolyCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_poly_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(GoodsPolyCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_poly_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsPolyCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_poly_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<GoodsPolyCategory> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_poly_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<GoodsPolyCategory> list, @Param("selective") GoodsPolyCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_poly_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GoodsPolyCategory selectOneByExample(GoodsPolyCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_poly_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GoodsPolyCategory selectOneByExampleWithBLOBs(GoodsPolyCategoryExample example);
}