package cn.bevol.statics.dao.mapper;

import cn.bevol.statics.dao.GoodsTagRule;
import cn.bevol.statics.dao.GoodsTagRuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GoodsTagRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     */
    long countByExample(GoodsTagRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     */
    int insert(GoodsTagRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     */
    int insertSelective(GoodsTagRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     */
    List<GoodsTagRule> selectByExampleWithBLOBsWithRowbounds(GoodsTagRuleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     */
    List<GoodsTagRule> selectByExampleWithBLOBs(GoodsTagRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     */
    List<GoodsTagRule> selectByExampleWithRowbounds(GoodsTagRuleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     */
    List<GoodsTagRule> selectByExample(GoodsTagRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     */
    GoodsTagRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GoodsTagRule record, @Param("example") GoodsTagRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") GoodsTagRule record, @Param("example") GoodsTagRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GoodsTagRule record, @Param("example") GoodsTagRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodsTagRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(GoodsTagRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsTagRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<GoodsTagRule> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<GoodsTagRule> list, @Param("selective") GoodsTagRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GoodsTagRule selectOneByExample(GoodsTagRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_goods_tag_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GoodsTagRule selectOneByExampleWithBLOBs(GoodsTagRuleExample example);
}